import type { Resource } from './models'

export const resources: Resource[] = [
  {
    id: 'aluminium',
    name: 'Aluminium',
    shortName: 'Al',
    category: 'inorganic',
    rarity: 'common',
    parentId: null,
    sortOrder: 1,
  },
  {
    id: 'beryllium',
    name: 'Beryllium',
    shortName: 'Be',
    category: 'inorganic',
    rarity: 'uncommon',
    parentId: 'aluminium',
    sortOrder: null,
  },
  {
    id: 'helium-3',
    name: 'Helium-3',
    shortName: 'He-3',
    category: 'inorganic',
    rarity: 'common',
    parentId: null,
    sortOrder: null,
  },
  {
    id: 'copper',
    name: 'Copper',
    shortName: 'Cu',
    category: 'inorganic',
    rarity: 'common',
    parentId: null,
    sortOrder: 4,
  },
  {
    id: 'silver',
    name: 'Silver',
    shortName: 'Ag',
    category: 'inorganic',
    rarity: 'uncommon',
    parentId: 'lead',
    sortOrder: 1,
  },
  {
    id: 'water',
    name: 'Water',
    shortName: 'H2O',
    category: 'inorganic',
    rarity: 'common',
    parentId: null,
    sortOrder: null,
  },
]
