import { buildReviewDraft } from './buildDraft.ts'

/** Independent Codex draft used by the German semantic review package. */
export const deDEReviewDraft = buildReviewDraft({
  "about.releaseNotes": "Versionshinweise",
  "cargo.destination.count.one": "{outpost} — {count} Frachtlink",
  "cargo.destination.count.few": "{outpost} — {count} Frachtlinks",
  "cargo.destination.count.other": "{outpost} — {count} Frachtlinks",
  "cargo.destination.incomplete": "{outpost} — Frachtlink auswählen",
  "cargo.pad.noRemoteLink": "keine entfernte Verbindung",
  "cargo.destination.missingOutpost": "Außenposten nicht verfügbar ({id})",
  "cargo.destination.missingPad": "Frachtlink nicht verfügbar ({id})",
  "cargo.pairing.records": "Verbindungseinträge",
  "cargo.pairing.remove": "Diese Verbindung entfernen",
  "cargo.pairing.removeLabel": "Verbindung {id} entfernen: {endpoints}",
  "validation.cargoDestinationIncomplete": "Wähle bei {destination} einen Frachtlink aus oder füge einen hinzu, um die Verbindung abzuschließen.",
  "validation.cargoMissingOutpost": "Der gewählte Außenposten ist nicht verfügbar ({id}). Wähle ein anderes Ziel oder keine Verbindung und prüfe vorhandene Verbindungseinträge.",
  "validation.cargoMissingPad": "Der gewählte Frachtlink bei {destination} ist nicht verfügbar ({id}). Wähle einen anderen, füge einen hinzu oder entferne den Verbindungseintrag.",
  "validation.cargoOrphan": "Kein Endpunkt ist vorhanden. Sichere deine Daten, korrigiere die Verbindung in einer exportierten Kopie und importiere sie erneut oder stelle einen gültigen Export wieder her.",
  "history.cargoDestination": "Frachtziel auswählen: {destination} ({outpost} / {pad})",
  "history.cargoConnect": "Frachtlinks verbinden ({outpost} / {pad})",
  "history.cargoRemoteAdd": "Entfernten Frachtlink erstellen und verbinden ({outpost} / {pad})",
  "history.cargoRepair": "Verbindung {id} entfernen ({outpost} / {pad})",
  "validation.cargoPairingConflict": "Widersprüchliche Frachtlink-Verbindungen.",
  'outpost.system.select': 'Auswählen...',
  'outpost.body.select': 'Auswählen...',
  "validation.activeProductionOrganicInvalidMany": "{resource} ist als produziert markiert, aber dieser Produzent ist auf diesem Planeten nicht für die organische Produktion geeignet.",
  "validation.activeProductionOrganicInvalidOne": "{resource} ist als produziert markiert, aber dieser Produzent ist auf diesem Planeten nicht für die organische Produktion geeignet.",
  "validation.activeProductionOrganicInvalid": "{resource} ist als produziert markiert, aber dieser Produzent ist auf diesem Planeten nicht für die organische Produktion geeignet.",
  "help.organic.unavailableBiomes": "{resource} ist von dieser domestizierbaren Spezies auf diesem Planeten nicht verfügbar.",
  "help.organic.unavailableBiome": "{resource} ist von dieser domestizierbaren Spezies auf diesem Planeten nicht verfügbar.",
  "help.organic.unavailablePlanet": "{resource} ist von dieser domestizierbaren Spezies auf diesem Planeten nicht verfügbar.",
  "help.organic.availableBiomes": "{resource} ist von einer domestizierbaren Spezies auf diesem Planeten erhältlich.",
  "help.organic.availableSelectedBiome": "{resource} ist von einer domestizierbaren Spezies auf diesem Planeten erhältlich.",
  "help.organic.availableBiome": "{resource} ist von einer domestizierbaren Spezies auf diesem Planeten erhältlich.",
  "help.organic.availablePlanet": "{resource} ist von einer domestizierbaren Spezies auf diesem Planeten erhältlich.",
  "help.biomes": "Die ausgewählten Biome beschränken die Verfügbarkeit anorganischer Ressourcen auf Ressourcen, die dort vorkommen können.",
  "about.version": "Version {version}",
  "about.build": "Build {commit}",
  "about.modified": "lokal / verändert",
  "about.unknown": "lokal / ungeprüft",
  "about.licenseSummary": "Projekteigener Code: GPL-3.0-or-later, ohne Gewährleistung. Für Grafiken und aus dem Spiel abgeleitete Inhalte gelten gesonderte Rechte.",
  "about.license": "Vollständige Lizenz",
  "about.notices": "Hinweise zu Drittanbietern",
  "about.repository": "Quellcode-Repository",
  "about.buildSource": "Quellcode dieses Builds",
  "about.issues": "Fehler und Vorschläge",
  "about.contact": "Privater / alternativer Kontakt",
  "about.support": "Gooberpede unterstützen",
  "about.funding": "Freiwillige Unterstützung der Bethesda-Mods und Werkzeuge des Entwicklers. Veröffentlichte Projekte sind kostenlos nutzbar; Trinkgelder oder Mitgliedschaften erwerben keine Zusatzfunktionen, exklusiven Inhalte, Zugänge, bevorzugten Support oder Lieferzusagen.",
  "about.backup": "Gespeichert in diesem Browserprofil auf dieser Website, ohne Kontosynchronisierung oder Serversicherung. Vor dem Löschen von Browserdaten oder einem Gerätewechsel exportieren. Ein Import ersetzt die Sammlung. Bei Speicherfehlern die Arbeit aus dem Arbeitsspeicher exportieren.",
  "about.unofficial": "Unabhängiges, inoffizielles Projekt; weder mit Bethesda Game Studios oder Microsoft verbunden noch von ihnen unterstützt.",
  "about.artwork": "Favicon-Grafik (gesonderte Lizenz):",
  'about.attribution': 'designed by gravisio from Flaticon',
  'referenceFatal.explanation': 'Erforderliche Referenzdaten konnten nicht ordnungsgemäß geladen werden. Der Tracker wurde angehalten, um deine gespeicherte Arbeit zu schützen.',
  'referenceFatal.privacy': 'Beim Melden wird deine E-Mail-App geöffnet und es werden nur technische Diagnosedaten eingefügt. Gespeicherte Netzwerkdaten werden nicht automatisch einbezogen.',
  'shortcuts.introduction': 'Globale Befehle, die in der gesamten Anwendung verfügbar sind. Bei der Texteingabe und in geöffneten Dialogen haben deren Funktionen Vorrang vor Tastenkürzeln.',
  'character.level.rejectedRestored': 'Ungültige Stufe. {value} wurde wiederhergestellt. Gib eine Stufe zwischen 1 und 999 ein.',
  'character.level.rejectedEmpty': 'Ungültige Stufe. Der vorherige Wert wurde wiederhergestellt. Gib eine Stufe zwischen 1 und 999 ein.',
  'character.skillRank.rejectedRestored': 'Ungültiger Rang. {value} wurde wiederhergestellt. Gib einen Rang zwischen 0 und 4 ein.',
  'character.skillRank.rejectedEmpty': 'Ungültiger Rang. Der vorherige Wert wurde wiederhergestellt. Gib einen Rang zwischen 0 und 4 ein.',
  'network.reset.explanation': 'Das aktuelle Netzwerk auf einen neuen Standardzustand zurücksetzen?',
  'network.delete.explanation': 'Das aktuelle Netzwerk aus dieser Sammlung entfernen?',
  'network.delete.undoHint': 'Du kannst diese Aktion während der aktuellen Sitzung rückgängig machen.',
  'matrix.column.present': 'Vorhanden',
  'matrix.column.producing': 'In Produktion',
  'matrix.column.inputs': 'Einsatzstoffe',
  'matrix.column.logistics': 'Logistik',
  'plannedSupply.heading': 'Geplante Versorgung',
  'cargo.pad.semanticSummary': 'Ziel: {destination}. Ausgehend: {outbound}. Eingehend: {inbound}. {linkType}.',
  'cargo.pad.count': '{count} {count, plural, one {Frachtlink} other {Frachtlinks}}',
  'validation.manufacturingInputUnavailable': '{product} benötigt {input}, aber {input} ist an diesem Außenposten nicht verfügbar.',
  'validation.plannedSupplyUnresolved': '{count} {count, plural, one {Element} other {Elemente}} in Geplante Versorgung: {itemList}.',
  'validation.issueCount': 'Validierung: {count} {count, plural, one {Problem} other {Probleme}}',
  'validation.remediation.extraction': 'Zur Gewinnung verfügbar in: {biomes}',
  "validation.remediation.harvesting": "Wähle einen gültigen domestizierbaren Produzenten auf diesem Planeten.",
  'validation.unresolvedCargoExport': 'Dieser Frachtexport hat keine tatsächliche Quelle.',
  'referenceFatal.diagnostic.asset': 'Datei',
  'referenceFatal.reason.assetContentType': 'Eine erforderliche Referenzdatei wurde mit dem falschen Inhaltstyp bereitgestellt.',
  'referenceFatal.reason.assetHash': 'Eine erforderliche Referenzdatei stimmt nicht mit dem Manifest überein.',
  'referenceFatal.reason.assetSize': 'Eine erforderliche Referenzdatei überschreitet die Größenbegrenzung.',
  'referenceFatal.reason.manifestVersion': 'Die Version des Referenzmanifests wird nicht unterstützt.',
  'status.import.fileTooLarge': 'Dieser Import ist zu groß, um ihn sicher zu öffnen.',
  'history.editManufacturing': 'Fertigung bei {outpost} bearbeiten',
  'history.unlinkCargoPad': 'Verbindung für {outpost} / {pad} trennen',
  'history.linkCargoPad': '{localOutpost} / {localPad} mit {remoteOutpost} / {remotePad} verbinden',
  'matrix.tooltip.export.inactive': '{item} wird nicht exportiert.',
  'cargo.interSystem.button': 'Intersystem',
  'validation.bodySystemMismatch': 'Der für diesen Außenposten ausgewählte Himmelskörper gehört nicht zum ausgewählten Sternsystem.',
  'validation.interstellarHelium3': 'Dieser Intersystem-Frachtlink sendet Fracht, aber an seinem Außenposten ist keine Helium-3-Versorgung verfügbar.',
  'validation.missingCargoEndpoint': 'Diese Frachtverbindung verweist auf einen fehlenden Außenposten oder Frachtlink-Endpunkt.',
  'validation.characterNameLength': 'Charakternamen in Starfield haben normalerweise höchstens 25 Zeichen.',
  'validation.outpostNameLength': 'Starfield begrenzt Außenpostennamen normalerweise auf 25 Zeichen; längere modifizierte Namen werden weiterhin unterstützt.',
  'validation.regularPadCrossSystem': 'Dieser Frachtlink ist mit einem Außenposten in einem anderen Sternsystem verbunden; verwende stattdessen einen Intersystem-Frachtlink.',
  'status.storage.recovery': 'Gespeicherte Browserdaten konnten nicht wiederhergestellt werden. Es wird eine temporäre Sammlung verwendet; das Original bleibt bis zu einer Bearbeitung erhalten.',
  'status.storage.unavailable': 'Der Browserspeicher ist nicht verfügbar. Diese Sammlung befindet sich nur im Arbeitsspeicher.',
  'status.storage.unsaved': 'Änderungen befinden sich nur im Arbeitsspeicher und wurden in diesem Browser nicht gespeichert.',
  'status.storage.capacity': 'Diese Sammlung ist zu groß, um sie sicher zu speichern. Änderungen verbleiben im Arbeitsspeicher.',
  'help.plannedSupply': 'Ausgewählte Elemente dienen als Platzhalter, bis eine lokale oder importierte Versorgung eingerichtet ist.',
  'help.logistics': 'Elemente, die derzeit Frachtlinks zugewiesen sind, werden hier angezeigt.',
  'help.present': 'Zeigt, ob eine Ressource an diesem Außenposten vorhanden sein kann.',
  'help.producing': 'Zeigt, ob dieser Außenposten derzeit für die Produktion der Ressource oder des Produkts konfiguriert ist.',
  'help.validation': 'Fehler kennzeichnen ungültige Zustände, Warnungen unvollständige oder inkonsistente Zustände und Informationen nützliche Folgeschritte.',
  'search.input.description': 'Gib einen Elementnamen oder eine Abkürzung ein und bestätige dann das zu suchende Element.',
  'search.results.dragInstructions': 'Verschiebe die Suchergebnisse mit den Pfeiltasten. Halte Shift für größere Schritte gedrückt.',
}, [
  ['Reference data unavailable', 'Referenzdaten nicht verfügbar'], ['Reference data', 'Referenzdaten'], ['reference data', 'Referenzdaten'],
  ['could not be', 'konnten nicht'], ['could not', 'konnte nicht'], ['Failed to load', 'Referenzdaten konnten nicht geladen werden:'],
  ['Keyboard Shortcuts', 'Tastenkürzel'], ['keyboard shortcuts', 'Tastenkürzel'], ['Resource Matrix', 'Ressourcenmatrix'],
  ['Planned Supply', 'Geplante Versorgung'], ['Inter-System Cargo Links', 'Intersystem-Frachtlinks'], ['Inter-System Cargo Link', 'Intersystem-Frachtlink'],
  ['Cargo Links', 'Frachtlinks'], ['Cargo Link', 'Frachtlink'], ['cargo links', 'Frachtlinks'], ['cargo link', 'Frachtlink'],
  ['Outpost Management', 'Außenposten-Verwaltung'], ['Outpost Engineering', 'Außenposten-Technik'], ['Planetary Habitation', 'Planetenbesiedlung'],
  ['Research Methods', 'Forschungsmethoden'], ['Special Projects', 'Spezialprojekte'], ['Active Production', 'Aktive Produktion'],
  ['Search Results', 'Suchergebnisse'], ['Outpost Details', 'Außenpostendetails'], ['outpost navigation', 'Außenpostennavigation'], ['Outpost Navigation', 'Außenpostennavigation'],
  ['Manufactured Products', 'Gefertigte Produkte'], ['manufactured product', 'gefertigtes Produkt'], ['Inorganic Resources', 'Anorganische Ressourcen'], ['Organic Resources', 'Organische Ressourcen'],
  ['No validation issues', 'Keine Validierungsprobleme'], ['validation details', 'Validierungsdetails'], ['star system', 'Sternsystem'], ['planetary body', 'Himmelskörper'],
  ['local resources', 'lokalen Ressourcen'], ['active production', 'aktiven Produktion'], ['explicit resource presence', 'expliziten Ressourcenvorkommen'],
  ['manufacturing list', 'Fertigungsliste'], ['outbound items', 'ausgehenden Elementen'], ['available for extraction', 'zur Gewinnung verfügbar'],
  ['available for harvesting', 'zur Ernte verfügbar'], ['not available', 'nicht verfügbar'], ['is available', 'ist verfügbar'],
  ['is being produced', 'wird produziert'], ['is not being produced', 'wird nicht produziert'], ['is being exported', 'wird exportiert'], ['is being imported', 'wird importiert'],
  ['Add items to', 'Elemente hinzufügen zu'], ['Remove all', 'Alle entfernen aus'], ['Add product', 'Produkt hinzufügen'], ['Add outpost', 'Außenposten hinzufügen'],
  ['Delete Outpost', 'Außenposten löschen'], ['New Outpost', 'Neuer Außenposten'], ['outposts', 'Außenposten'], ['outpost', 'Außenposten'], ['Outposts', 'Außenposten'], ['Outpost', 'Außenposten'],
  ['NETWORK', 'NETZWERK'], ['Network', 'Netzwerk'], ['network', 'Netzwerk'], ['collection', 'Sammlung'], ['Language and region', 'Sprache und Region'], ['Automatic', 'Automatisch'], ['Locale', 'Gebietsschema'],
  ['Reload', 'Neu laden'], ['Report', 'Melden'], ['Error code', 'Fehlercode'], ['HTTP status', 'HTTP-Status'], ['Media type', 'Medientyp'],
  ['Manifest schema version', 'Manifest-Schemaversion'], ['Expected dataset ID', 'Erwartete Datensatz-ID'], ['Actual dataset ID', 'Tatsächliche Datensatz-ID'],
  ['Expected hash prefix', 'Erwartetes Hash-Präfix'], ['Actual hash prefix', 'Tatsächliches Hash-Präfix'], ['About', 'Info'], ['Help', 'Hilfe'],
  ['Close', 'Schließen'], ['Cancel', 'Abbrechen'], ['cancel', 'abbrechen'], ['save', 'speichern'], ['edit', 'bearbeiten'], ['Add', 'Hinzufügen'], ['Remove', 'Entfernen'],
  ['Move', 'Verschieben'], ['Drag', 'Ziehen'], ['Expand', 'Erweitern'], ['Collapse', 'Reduzieren'], ['Show', 'Anzeigen'], ['Hide', 'Ausblenden'],
  ['History', 'Verlauf'], ['Search', 'Suche'], ['Workspace', 'Arbeitsbereich'], ['Import', 'Importieren'], ['Export', 'Exportieren'], ['Validation', 'Validierung'],
  ['Undo', 'Rückgängig'], ['Redo', 'Wiederholen'], ['Focus', 'Fokus auf'], ['Previous', 'Vorheriger'], ['Next', 'Nächster'], ['Toggle', 'Umschalten'], ['details', 'Details'], ['Navigation', 'Navigation'],
  ['Character', 'Charakter'], ['Level', 'Stufe'], ['rank', 'Rang'], ['level', 'Stufe'], ['Active', 'Aktiv'], ['Reset', 'Zurücksetzen'], ['Delete', 'Löschen'],
  ['Lock order', 'Reihenfolge sperren'], ['Reshuffle', 'Neu anordnen'], ['reshuffling', 'Neuanordnen von'], ['Select', 'Auswählen'], ['System', 'System'], ['Body', 'Himmelskörper'],
  ['Solar', 'Solar'], ['Wind', 'Wind'], ['Biomes', 'Biome'], ['Very Poor', 'Sehr schlecht'], ['V.Poor', 'S. schlecht'], ['Poor', 'Schlecht'], ['Normal', 'Normal'],
  ['Good', 'Gut'], ['None', 'Keine'], ['Unknown', 'Unbekannt'], ['output', 'Leistung'], ['no modifier', 'ohne Modifikator'], ['Item', 'Element'], ['Source', 'Quelle'],
  ['Present', 'Vorhanden'], ['Producing', 'In Produktion'], ['Inputs', 'Einsatzstoffe'], ['Logistics', 'Logistik'], ['Inorganic', 'Anorganisch'], ['Organic', 'Organisch'],
  ['Manufacturing', 'Fertigung'], ['Imports', 'Importe'], ['Exports', 'Exporte'], ['Unspecified', 'Nicht angegeben'], ['No local resources have been selected', 'Es wurden keine lokalen Ressourcen ausgewählt'],
  ['No manufacturing recorded', 'Keine Fertigung erfasst'], ['No imports', 'Keine Importe'], ['No exports', 'Keine Exporte'], ['No planned supply', 'Keine geplante Versorgung'],
  ['active', 'aktiv'], ['inactive', 'inaktiv'], ['Destination', 'Ziel'], ['Unlinked', 'Nicht verbunden'], ['unlinked', 'nicht verbunden'], ['linked to', 'verbunden mit'], ['Linked to', 'Verbunden mit'],
  ['nothing', 'nichts'], ['No items available to export', 'Keine Elemente zum Exportieren verfügbar'], ['No outbound cargo', 'Keine ausgehende Fracht'], ['No inbound cargo', 'Keine eingehende Fracht'],
  ['Standard', 'Standard'], ['All', 'Alle'], ['Errors', 'Fehler'], ['Warnings', 'Warnungen'], ['Warning', 'Warnung'], ['Error', 'Fehler'], ['Info', 'Information'],
  ['Open', 'Öffnen'], ['issues', 'Probleme'], ['issue', 'Problem'], ['errors', 'Fehler'], ['warnings', 'Warnungen'], ['requires', 'benötigt'], ['recorded', 'erfasst'],
  ['missing', 'fehlend'], ['unknown', 'unbekannt'], ['appears more than once', 'kommt mehrfach vor'], ['Selected file', 'Ausgewählte Datei'], ['selected file', 'ausgewählte Datei'],
  ['selected collection', 'ausgewählte Sammlung'], ['Browser storage', 'Browserspeicher'], ['Changes', 'Änderungen'], ['Dismiss', 'Schließen'], ['Exported', 'Exportiert'], ['Imported', 'Importiert'],
  ['Import failed for', 'Import fehlgeschlagen für'], ['does not contain', 'enthält keine'], ['contains', 'enthält'], ['invalid', 'ungültig'], ['Unsupported', 'Nicht unterstützte'],
  ['Nothing to undo', 'Nichts rückgängig zu machen'], ['Nothing to redo', 'Nichts zu wiederholen'], ['Rename', 'Umbenennen'], ['Clear', 'Leeren'], ['Set', 'Setzen'], ['Change', 'Ändern'],
  ['Start producing', 'Produktion starten:'], ['Stop producing', 'Produktion beenden:'], ['Available from', 'Verfügbar von'], ['available', 'verfügbar'], ['selected', 'ausgewählt'],
  ['Resource', 'Ressource'], ['Product', 'Produkt'], ['resource', 'Ressource'], ['product', 'Produkt'], ['Search for', 'Suchen nach'], ['Type an item name', 'Elementnamen eingeben'], ['was found at', 'wurde gefunden bei'],
  ['was not found at any', 'wurde an keinem gefunden:'], ['Missing Inputs', 'Fehlende Einsatzstoffe'], ['Importing', 'Importiert'], ['Exporting', 'Exportiert'],
])
