import { buildReviewDraft } from './buildDraft.ts'

/** Independent Spanish (Spain) Codex draft used only by the semantic review package. */
export const esESReviewDraft = buildReviewDraft({
  "about.releaseNotes": "Notas de la versión",
  "cargo.destination.count.one": "{outpost} — {count} enlace de cargamento",
  "cargo.destination.count.few": "{outpost} — {count} enlaces de cargamento",
  "cargo.destination.count.other": "{outpost} — {count} enlaces de cargamento",
  "cargo.destination.incomplete": "{outpost} — elegir enlace de cargamento",
  "cargo.pad.noRemoteLink": "sin conexión remota",
  "cargo.destination.missingOutpost": "Puesto no disponible ({id})",
  "cargo.destination.missingPad": "Enlace de cargamento no disponible ({id})",
  "cargo.pairing.records": "Registros de conexión",
  "cargo.pairing.remove": "Eliminar esta conexión",
  "cargo.pairing.removeLabel": "Eliminar conexión {id}: {endpoints}",
  "validation.cargoDestinationIncomplete": "Elige o añade un enlace de cargamento en {destination} para completar esta conexión.",
  "validation.cargoMissingOutpost": "El puesto seleccionado no está disponible ({id}). Elige otro destino o Sin conexión; revisa los registros conservados.",
  "validation.cargoMissingPad": "El enlace de cargamento seleccionado en {destination} no está disponible ({id}). Elige otro, añade uno o elimina su registro de conexión.",
  "validation.cargoOrphan": "No existe ninguno de los extremos. Conserva tus datos, corrige la conexión en una copia exportada e impórtala, o restaura una exportación válida.",
  "history.cargoDestination": "Elegir destino de carga: {destination} ({outpost} / {pad})",
  "history.cargoConnect": "Conectar enlaces de cargamento ({outpost} / {pad})",
  "history.cargoRemoteAdd": "Crear y conectar enlace de cargamento remoto ({outpost} / {pad})",
  "history.cargoRepair": "Eliminar conexión {id} ({outpost} / {pad})",
  "validation.cargoPairingConflict": "Conexiones de carga contradictorias.",
  'validation.cargoPadLinkedMultiple': 'Este enlace de cargamento tiene más de una conexión.',
  "about.version": "Versión {version}",
  "about.build": "Compilación {commit}",
  "about.modified": "local / modificada",
  "about.unknown": "local / sin verificar",
  "about.licenseSummary": "Código creado para el proyecto: GPL-3.0-or-later, sin garantía. Las ilustraciones y el contenido derivado del juego están sujetos a derechos separados.",
  "about.license": "Licencia completa",
  "about.notices": "Avisos de terceros",
  "about.repository": "Repositorio del código fuente",
  "about.buildSource": "Fuente de esta compilación",
  "about.issues": "Errores y sugerencias",
  "about.contact": "Contacto privado / alternativo",
  "about.support": "Apoyar a Gooberpede",
  "about.funding": "Apoyo voluntario al trabajo del desarrollador en mods y herramientas para juegos de Bethesda. Los proyectos publicados son gratuitos; las propinas o suscripciones no compran funciones adicionales, exclusivas, acceso, asistencia prioritaria ni compromisos de entrega.",
  "about.backup": "Los datos se guardan en este perfil del navegador para este sitio, sin sincronización de cuenta ni copia en el servidor. Exporta antes de borrar los datos del navegador o cambiar de dispositivo. La importación sustituye la colección. Si falla el guardado, exporta el trabajo que está en memoria.",
  "about.unofficial": "Proyecto independiente y no oficial, sin afiliación ni aprobación de Bethesda Game Studios o Microsoft.",
  "about.artwork": "Ilustración del icono del sitio (licencia separada):",
  'about.attribution': 'designed by gravisio from Flaticon',
  'referenceFatal.explanation': 'Los datos de referencia obligatorios no se han podido cargar correctamente. El rastreador se ha detenido para proteger el trabajo guardado.',
  'referenceFatal.privacy': 'Al informar se abre la aplicación de correo y solo se incluyen diagnósticos técnicos. No se adjunta automáticamente ningún dato guardado de la red.',
  'shortcuts.introduction': 'Comandos globales disponibles en toda la aplicación. Los atajos ceden prioridad a la edición de texto y a los cuadros de diálogo abiertos cuando corresponde.',
  'character.level.rejectedRestored': 'Nivel no válido. Se ha restaurado {value}. Introduce un nivel del 1 al 999.',
  'character.level.rejectedEmpty': 'Nivel no válido. Se ha restaurado el valor anterior. Introduce un nivel del 1 al 999.',
  'character.skillRank.rejectedRestored': 'Rango no válido. Se ha restaurado {value}. Introduce un rango del 0 al 4.',
  'character.skillRank.rejectedEmpty': 'Rango no válido. Se ha restaurado el valor anterior. Introduce un rango del 0 al 4.',
  'network.reset.explanation': '¿Restablecer la red actual a un estado predeterminado nuevo?',
  'network.delete.explanation': '¿Eliminar la red actual de esta colección?',
  'network.delete.undoHint': 'Puedes deshacer esta acción durante la sesión actual.',
  'matrix.column.present': 'Presencia',
  'matrix.column.producing': 'En producción',
  'matrix.column.inputs': 'Materiales de entrada',
  'matrix.column.logistics': 'Logística',
  'plannedSupply.heading': 'Suministro planificado',
  'cargo.pad.semanticSummary': 'Destino: {destination}. Saliente: {outbound}. Entrante: {inbound}. {linkType}.',
  'cargo.pad.count': '{count} {count, plural, one {enlace de cargamento} other {enlaces de cargamento}}',
  'validation.issueCount': 'Validación: {count} {count, plural, one {incidencia} other {incidencias}}',
  'validation.manufacturingInputUnavailable': '{product} necesita {input}, pero {input} no está disponible en este puesto.',
  'validation.plannedSupplyUnresolved': '{count} {count, plural, one {elemento} other {elementos}} en Suministro planificado: {itemList}.',
  "validation.activeProductionOrganicInvalid": "{resource} figura en producción, pero este productor no es apto para la producción orgánica en este planeta.",
  'validation.activeProductionInorganicInvalid': '{resource} figura en producción, pero no se puede extraer en el puesto en {biomes}.',
  "validation.activeProductionOrganicInvalidOne": "{resource} figura en producción, pero este productor no es apto para la producción orgánica en este planeta.",
  "validation.activeProductionOrganicInvalidMany": "{resource} figura en producción, pero este productor no es apto para la producción orgánica en este planeta.",
  'validation.activeProductionInorganicInvalidOne': '{resource} figura en producción, pero no se puede extraer en el puesto en el bioma {biomes}.',
  'validation.activeProductionInorganicInvalidMany': '{resource} figura en producción, pero no se puede extraer en el puesto en los biomas {biomes}.',
  'validation.bodySystemMismatch': 'El cuerpo celeste seleccionado para este puesto no pertenece al sistema estelar seleccionado.',
  'validation.cargoPadSkillLimit': 'Este puesto tiene {count} enlaces de cargamento, pero el nivel actual de {skill} permite un máximo de {limit}.',
  'validation.duplicateOutpostName': 'Hay {count} puestos llamados «{name}». Se recomiendan nombres únicos para evitar ambigüedades.',
  'validation.interstellarHelium3': 'Este enlace de cargamento intersistema envía carga, pero su puesto no dispone de suministro de Helio-3.',
  'validation.invalidCharacterLevel': 'El nivel del personaje es {level}, pero un nivel registrado debe ser un número entero del {minimum} al {maximum}.',
  'validation.invalidSkillLevel': '{skill} tiene el nivel {level}, pero los niveles válidos son números enteros del {minimum} al {maximum}.',
  'validation.missingCargoEndpoint': 'Esta conexión de carga hace referencia a un puesto o extremo de enlace de cargamento inexistente.',
  'validation.organicInputUnavailable': '{species} necesita {input}, pero {input} no está disponible en este puesto.',
  'validation.outpostBodyNotEligible': 'Este puesto se encuentra en un cuerpo celeste que no admite puestos.',
  'validation.characterNameLength': 'Los nombres de personaje de Starfield suelen tener un máximo de 25 caracteres.',
  'validation.outpostNameLength': 'Starfield limita normalmente los nombres de los puestos a 25 caracteres; se siguen admitiendo nombres más largos añadidos mediante mods.',
  'validation.outpostSkillLimit': 'Esta red tiene {count} puestos, pero el nivel actual de {skill} permite un máximo de {limit}.',
  'validation.planetaryHabitationRequirement': 'Este puesto requiere el rango {required} de {skill}, pero el rango de personaje registrado es {recorded}.',
  'validation.regularPadCrossSystem': 'Este enlace de cargamento está conectado a un puesto de otro sistema estelar; usa en su lugar un enlace de cargamento intersistema.',
  'validation.selectedBiomeInvalid': 'El bioma seleccionado pertenece a otro cuerpo celeste.',
  'validation.selfLinkedCargoPad': 'Esta conexión de carga usa el mismo enlace de cargamento en ambos extremos.',
  'validation.unspecifiedOrganicSource': '{resource} figura en producción, pero no se ha especificado un origen de flora o fauna.',
  'validation.unresolvedCargoExport': 'Esta exportación de carga no tiene un origen real.',
  'validation.xTechCapabilityProduced': '{resource} figura en producción, pero el personaje no tiene la capacidad de extracción necesaria.',
  'validation.xTechCapabilityPresent': '{resource} figura como presente, pero el personaje no tiene la capacidad de extracción necesaria.',
  'validation.xTechRequiresPresence': '{resource} figura en producción, pero no consta expresamente como presente en este puesto.',
  'validation.remediation.extraction': 'Disponible para extracción en: {biomes}',
  "validation.remediation.harvesting": "Elige un productor domesticable válido de este planeta.",
  'validation.remediation.organicSources': 'Disponible en: {sources}',
  'status.storage.recovery': 'No se han podido restaurar los datos guardados en el navegador. Se usa una colección temporal; el original se conservará hasta que se realice una edición.',
  'status.storage.unavailable': 'El almacenamiento del navegador no está disponible. Esta colección solo está en la memoria.',
  'status.storage.unsaved': 'Los cambios solo están en la memoria y no se han guardado en este navegador.',
  'status.storage.capacity': 'Esta colección es demasiado grande para guardarla de forma segura. Los cambios permanecen en la memoria.',
  'status.referenceData.loaded': 'Datos de referencia cargados: {systems} sistemas, {bodies} cuerpos celestes, {resources} recursos y {products} productos.',
  'help.plannedSupply': 'Los elementos seleccionados actúan como marcadores hasta que se establece un suministro local o importado.',
  'help.logistics': 'Aquí se muestran los elementos asignados actualmente a enlaces de cargamento.',
  "help.biomes": "Los biomas seleccionados limitan la disponibilidad de recursos inorgánicos a los que pueden aparecer en ellos.",
  'help.present': 'Indica si un recurso puede estar presente en este puesto.',
  'help.producing': 'Indica si este puesto está configurado actualmente para producir el recurso o producto.',
  'help.interSystem': 'Los enlaces de cargamento intersistema conectan puestos de distintos sistemas estelares y necesitan Helio-3.',
  'help.validation': 'Los errores identifican estados no válidos, las advertencias estados incompletos o incoherentes y la información señala acciones de seguimiento útiles.',
  'search.input.description': 'Escribe el nombre o la abreviatura de un elemento y confirma el elemento que quieres buscar.',
  'search.results.dragInstructions': 'Mueve los resultados de búsqueda con las teclas de flecha. Mantén pulsada Shift para avanzar más.',
  'referenceFatal.report.body': 'El rastreador se detuvo durante la verificación de los datos de referencia. Diagnósticos técnicos:',
  'referenceFatal.reason.manifestFetch': 'No se ha podido recuperar el manifiesto de referencia.',
  'referenceFatal.reason.manifestInvalid': 'El manifiesto de referencia no es válido.',
  'referenceFatal.reason.manifestVersion': 'La versión del manifiesto de referencia no es compatible.',
  'referenceFatal.reason.buildMismatch': 'Los datos de referencia pertenecen a otra compilación de la aplicación.',
  'referenceFatal.reason.internal': 'No se ha podido completar la comprobación de integridad de los datos de referencia.',
  'common.moveUp': 'Subir {item}', 'common.moveDown': 'Bajar {item}', 'common.dragToReorder': 'Arrastra {item} para reordenar',
  'about.description': 'Una herramienta para registrar redes de puestos de Starfield.',
  'shortcuts.action.focusSearch': 'Enfocar la búsqueda de elementos',
  'outpost.name.label': 'Nombre del puesto', 'outpost.system.select': 'Selecciona...', 'outpost.body.select': 'Selecciona...',
  'outpost.referenceData.empty': 'No se han encontrado datos de referencia de recursos para este cuerpo celeste.',
  'production.empty': 'No se han seleccionado recursos locales.',
  'matrix.action.togglePresent': 'Alternar la presencia de {item}', 'matrix.action.toggleProducing': 'Alternar la producción de {item}',
  'matrix.action.toggleProducingSource': 'Alternar la producción de {item} desde {source}',
  'plannedSupply.remove': 'Eliminar {item} de Suministro planificado', 'plannedSupply.add': 'Añadir {item} a Suministro planificado',
  'cargo.export.toggle': 'Alternar la exportación de {item}', 'cargo.destination.noPads': '{outpost} — sin enlaces de cargamento',
  'validation.duplicateLocalResource': '{item} aparece más de una vez en los recursos locales de este puesto.',
  'validation.duplicateActiveProduction': '{item} aparece más de una vez en la producción activa de este puesto.',
  'validation.duplicateExplicitPresence': '{item} aparece más de una vez en la presencia explícita de recursos de este puesto.',
  'validation.duplicateBiome': '{item} aparece más de una vez en la selección de biomas de este puesto.',
  'validation.duplicateManufacturing': '{item} aparece más de una vez en la lista de fabricación de este puesto.',
  'validation.duplicatePlannedSupply': '{item} aparece más de una vez en el Suministro planificado de este puesto.',
  'validation.duplicateOutboundItem': '{item} aparece más de una vez entre los elementos salientes de este enlace de cargamento.',
  'validation.unknownSystem': 'Este puesto hace referencia al ID de sistema estelar desconocido «{id}».',
  'validation.unknownBody': 'Este puesto hace referencia al ID de cuerpo celeste desconocido «{id}».',
  'validation.unknownLocalResource': 'Este puesto hace referencia al ID de recurso desconocido «{id}» en sus recursos locales.',
  'validation.unknownBiome': 'Este puesto hace referencia al ID de bioma corporal desconocido «{id}».',
  'validation.unknownExplicitResource': 'Este puesto hace referencia al ID de recurso desconocido «{id}» en su presencia explícita de recursos.',
  'validation.unknownProductionResource': 'Este puesto hace referencia al ID de recurso desconocido «{id}» en su producción activa.',
  'validation.unknownProductionSpecies': 'Este puesto hace referencia al ID de especie desconocido «{id}» en su producción activa.',
  'validation.unknownManufacturingProduct': 'Este puesto hace referencia al ID de producto desconocido «{id}» en su lista de fabricación.',
  'validation.unknownPlannedItem': 'Este puesto hace referencia al ID de {kind} desconocido «{id}» en Suministro planificado.',
  'validation.unknownOutboundItem': 'Este enlace de cargamento hace referencia al ID de {kind} desconocido «{id}» en sus elementos salientes.',
  'status.import.failed': 'Error al importar {fileName}: {reason}', 'status.import.readFailed': 'No se ha podido leer el archivo seleccionado.',
  'status.import.invalid': 'No se ha podido importar el archivo seleccionado.', 'status.import.invalidJson': 'El archivo seleccionado no contiene JSON válido.',
  'status.import.invalidCollection': 'El archivo seleccionado no es una colección de redes válida.',
  'status.import.emptyCollection': 'La colección seleccionada no contiene ninguna red.',
  'status.import.malformedEntry': 'La colección seleccionada contiene una entrada de red con formato incorrecto.',
  'status.import.duplicateNetworkId': 'La colección seleccionada contiene el ID de red duplicado «{id}».',
  'status.import.invalidCharacter': 'El archivo seleccionado contiene datos de personaje no válidos.',
  'status.import.invalidCapabilities': 'El archivo seleccionado contiene datos de capacidades del personaje no válidos.',
  'status.import.invalidSkills': 'El archivo seleccionado contiene datos de habilidades del personaje no válidos.',
  'status.import.invalidNetwork': 'El archivo seleccionado no es una red de puestos válida.',
  'status.import.invalidOutpost': 'El archivo seleccionado contiene un puesto no válido.',
  'status.import.invalidExplicitPresence': 'El archivo seleccionado contiene datos de presencia explícita de recursos no válidos.',
  'status.import.invalidCargoPad': 'El archivo seleccionado contiene un enlace de cargamento no válido.',
  'status.import.invalidStructure': 'El archivo seleccionado contiene datos de red con formato incorrecto.',
  'status.import.invalidIdentity': 'El archivo seleccionado contiene un identificador estable vacío o duplicado.',
  'status.import.fileTooLarge': 'Esta importación es demasiado grande para abrirla de forma segura.',
  'status.import.arrayLimitExceeded': 'Esta importación contiene demasiados elementos en una sección.',
  'status.import.tooManyNetworks': 'Esta importación contiene demasiadas redes guardadas.',
  'status.import.aggregateLimitExceeded': 'Esta importación contiene demasiados elementos para abrirla de forma segura.',
  'status.import.stringTooLong': 'Esta importación contiene un valor de texto demasiado largo.',
  'status.referenceData.reload': 'Volver a cargar los datos de referencia', 'status.drag.reorder': 'Suelta para reordenar · Esc para cancelar',
  'transfer.import.tooltip': 'Importar todas las redes desde JSON',
  'history.unlinkCargoPad': 'Desvincular {outpost} / {pad}', 'history.linkCargoPad': 'Vincular {localOutpost} / {localPad} con {remoteOutpost} / {remotePad}',
  'history.changeCargoLink': 'Cambiar el enlace de {localOutpost} / {localPad} a {remoteOutpost} / {remotePad}',
  'history.renameCharacter': 'Cambiar el nombre del personaje de {previousName} a {name}',
  'history.changeCharacterLevel': 'Cambiar el nivel del personaje de {previousLevel} a {level}', 'history.changeSkill': 'Cambiar {skill} de {previousRank} a {rank}',
  'history.moveOutpost': 'Mover {outpost} a la posición {position}', 'history.moveCargoPad': 'Mover {outpost} / {pad} a la posición {position}',
  'history.addExport': 'Añadir la exportación {item} a {outpost} / {pad}', 'history.removeExport': 'Eliminar la exportación {item} de {outpost} / {pad}',
  'history.changeCargoPadType': 'Cambiar {outpost} / {pad} a {type}', 'history.renameOutpost': 'Cambiar el nombre del puesto de {previousName} a {name}',
  'history.changeSystem': 'Cambiar el sistema de {outpost} a {system}', 'history.clearSystem': 'Borrar el sistema de {outpost}',
  'history.changeBody': 'Cambiar el cuerpo celeste de {outpost} a {body}', 'history.clearBody': 'Borrar el cuerpo celeste de {outpost}',
  'history.addBiome': 'Añadir selección de bioma a {outpost}', 'history.removeBiome': 'Eliminar selección de bioma de {outpost}',
  'history.addLocalResource': 'Añadir el recurso local {resource} a {outpost}', 'history.removeLocalResource': 'Eliminar el recurso local {resource} de {outpost}',
  'history.addExplicitResource': 'Añadir el recurso explícito {resource} a {outpost}', 'history.removeExplicitResource': 'Eliminar el recurso explícito {resource} de {outpost}',
  'history.startProducing': 'Empezar a producir {resource} en {outpost}', 'history.stopProducing': 'Dejar de producir {resource} en {outpost}',
  'history.editManufacturing': 'Editar la fabricación en {outpost}',
  'help.forContext': 'Ayuda de {context}', 'help.contextLabel': 'Ayuda de {context}',
  "help.organic.unavailablePlanet": "{resource} no está disponible en esta especie domesticable de este planeta.",
  "help.organic.unavailableBiome": "{resource} no está disponible en esta especie domesticable de este planeta.",
  "help.organic.unavailableBiomes": "{resource} no está disponible en esta especie domesticable de este planeta.",
  "help.organic.availablePlanet": "{resource} está disponible en una especie domesticable de este planeta.",
  "help.organic.availableBiome": "{resource} está disponible en una especie domesticable de este planeta.",
  "help.organic.availableSelectedBiome": "{resource} está disponible en una especie domesticable de este planeta.",
  "help.organic.availableBiomes": "{resource} está disponible en una especie domesticable de este planeta.",
  'help.inorganicPresentRecorded': '{resource} consta como presente en este puesto.', 'help.inorganicPresentPossible': '{resource} puede estar presente en este puesto.',
  'matrix.action.xTech.add': 'Añadir {resource} como presente',
  'matrix.tooltip.xTech.add': 'Añade {resource} como presente. Puede extraerse en cualquier puesto si hay núcleos de energía de X-Tech disponibles.',
  'matrix.tooltip.xTech.present': '{resource} consta expresamente como presente en este puesto.',
  'matrix.tooltip.producing.active': '{item} se está produciendo en este puesto.', 'matrix.tooltip.producing.inactive': '{item} no se está produciendo en este puesto.',
  'matrix.tooltip.manufacturing.blocked': '{item} no se está produciendo en este puesto porque faltan materiales de entrada.',
  'matrix.tooltip.input.available': '{item} está disponible en este puesto.', 'matrix.tooltip.input.unavailable': '{item} no está disponible en este puesto.',
  'matrix.tooltip.export.active': '{item} se está exportando a {destinations}.',
  'search.input.label': 'Buscar recursos o productos en tus puestos.', 'search.submit': 'Buscar elemento',
  'search.results.found': '{searchItem} se ha encontrado en {count} {count, plural, one {puesto} other {puestos}}.',
  'referenceFatal.report.subject': 'Problema con los datos de referencia del rastreador de puestos de Starfield',
  'about.closeDialog': 'Cerrar el cuadro de diálogo Acerca de', 'shortcuts.closeDialog': 'Cerrar el cuadro de diálogo Atajos de teclado',
  'shortcuts.action.toggleNavigation': 'Mostrar u ocultar la navegación', 'shortcuts.action.focusNavigation': 'Enfocar la navegación',
  'shortcuts.action.toggleValidation': 'Alternar los detalles de validación',
  'network.reset.confirmTitle': 'RESTABLECER RED', 'network.delete.confirmTitle': 'ELIMINAR RED',
  'outpost.navigation.finishReshuffle': 'Terminar de reordenar los puestos', 'cargo.finishReshuffle': 'Terminar de reordenar los enlaces de cargamento',
  'validation.counts': '{errors} errores · {warnings} advertencias · {info} información',
  'status.dismiss': 'Descartar el mensaje de estado',
  'status.import.unsupportedCollectionSchema': 'Versión del esquema de colección de redes no compatible: {version}',
  'status.import.unsupportedNetworkSchema': 'Versión del esquema de red no compatible: {version}',
  'status.referenceData.failed': 'No se han podido cargar los datos de referencia.',
  'transfer.export.tooltip': 'Exportar todas las redes a JSON', 'history.importNetworks': 'Importar redes',
  'history.clearCharacterLevel': 'Borrar el nivel del personaje', 'history.setCharacterLevel': 'Establecer el nivel del personaje en {level}',
  'search.input.placeholder': 'Buscar recursos o productos', 'search.results.flag.missingInputs': 'Faltan materiales de entrada',
  'outpost.navigation.addWithLimit': 'Añadir puesto ({count} de {limit})',
  'cargo.expandAll': 'Expandir todo', 'cargo.collapseAll': 'Contraer todo',
  'cargo.addWithLimit': 'Añadir enlace de cargamento ({count} de {limit})', 'history.setSkill': 'Establecer {skill} en {rank}',
  'cargo.interSystem.button': 'Intersistema',
}, [
  ['Reference data unavailable', 'Datos de referencia no disponibles'], ['Required reference data', 'Los datos de referencia obligatorios'],
  ['Reference data', 'Datos de referencia'], ['reference data', 'datos de referencia'], ['reference manifest', 'manifiesto de referencia'],
  ['could not be retrieved', 'no se ha podido recuperar'], ['could not complete', 'no se ha podido completar'], ['is unsupported', 'no es compatible'],
  ['is invalid', 'no es válido'], ['belongs to a different app build', 'pertenece a otra compilación de la aplicación'],
  ['A required reference file', 'Un archivo de referencia obligatorio'], ['contains invalid JSON', 'contiene JSON no válido'],
  ['has an invalid structure', 'tiene una estructura no válida'], ['exceeds the size limit', 'supera el límite de tamaño'],
  ['does not match the manifest', 'no coincide con el manifiesto'], ['was served with the wrong content type', 'se ha servido con un tipo de contenido incorrecto'],
  ['Language and region', 'Idioma y región'], ['Automatic', 'Automático'], ['Locale', 'Configuración regional'],
  ['Keyboard Shortcuts', 'Atajos de teclado'], ['Resource Matrix', 'Matriz de recursos'], ['Planned Supply', 'Suministro planificado'],
  ['Active Production', 'Producción activa'], ['Inter-System Cargo Links', 'Enlaces de cargamento intersistema'],
  ['Inter-System Cargo Link', 'Enlace de cargamento intersistema'], ['Cargo Links', 'Enlaces de cargamento'], ['Cargo Link', 'Enlace de cargamento'],
  ['cargo links', 'enlaces de cargamento'], ['cargo link', 'enlace de cargamento'], ['Outpost Management', 'Gestión de puestos'],
  ['Outpost Engineering', 'Ingeniería de puestos'], ['Planetary Habitation', 'Asentamiento planetario'],
  ['Research Methods', 'Mét. de investigación'], ['Special Projects', 'Proyectos especiales'],
  ['Outpost Navigation', 'Navegación por puestos'], ['Outpost Details', 'Detalles del puesto'], ['outpost navigation', 'navegación por puestos'],
  ['Manufactured Products', 'Productos fabricados'], ['Inorganic Resources', 'Recursos inorgánicos'], ['Organic Resources', 'Recursos orgánicos'],
  ['Search Results', 'Resultados de búsqueda'], ['No validation issues', 'No hay incidencias de validación'], ['validation details', 'detalles de validación'],
  ['star system', 'sistema estelar'], ['planetary body', 'cuerpo celeste'], ['local resources', 'recursos locales'],
  ['active production', 'producción activa'], ['explicit resource presence', 'presencia explícita de recursos'],
  ['manufacturing list', 'lista de fabricación'], ['outbound items', 'elementos salientes'],
  ['appears more than once in', 'aparece más de una vez en'], ['refers to unknown', 'hace referencia a un'], ['unknown', 'desconocido'],
  ['is recorded as produced', 'figura en producción'], ['is recorded as present', 'figura como presente'], ['is not available', 'no está disponible'],
  ['is available', 'está disponible'], ['is being produced', 'se está produciendo'], ['is not being produced', 'no se está produciendo'],
  ['is being exported', 'se está exportando'], ['is not being exported', 'no se está exportando'], ['is being imported', 'se está importando'],
  ['available for extraction', 'disponible para extracción'], ['available for harvesting', 'disponible para recolección'],
  ['Add items to', 'Añadir elementos a'], ['Remove all', 'Eliminar todo'], ['Add manufactured product', 'Añadir producto fabricado'],
  ['Add product', 'Añadir producto'], ['Add outpost', 'Añadir puesto'], ['Delete Outpost', 'Eliminar puesto'], ['New Outpost', 'Nuevo puesto'],
  ['outposts', 'puestos'], ['outpost', 'puesto'], ['Outposts', 'Puestos'], ['Outpost', 'Puesto'],
  ['NETWORK', 'RED'], ['Network', 'Red'], ['network', 'red'], ['collection', 'colección'],
  ['Reload', 'Volver a cargar'], ['Report', 'Informar'], ['Error code', 'Código de error'], ['Asset', 'Archivo'],
  ['HTTP status', 'Estado HTTP'], ['Media type', 'Tipo de contenido'], ['Manifest schema version', 'Versión del esquema del manifiesto'],
  ['Expected dataset ID', 'ID esperado del conjunto de datos'], ['Actual dataset ID', 'ID real del conjunto de datos'],
  ['Expected hash prefix', 'Prefijo de hash esperado'], ['Actual hash prefix', 'Prefijo de hash real'],
  ['About', 'Acerca de'], ['Help', 'Ayuda'], ['Close', 'Cerrar'], ['Cancel', 'Cancelar'], ['cancel', 'cancelar'],
  ['save', 'guardar'], ['edit', 'editar'], ['Add', 'Añadir'], ['Remove', 'Eliminar'], ['Move', 'Mover'], ['Drag', 'Arrastrar'],
  ['Expand', 'Expandir'], ['Collapse', 'Contraer'], ['Show', 'Mostrar'], ['Hide', 'Ocultar'], ['History', 'Historial'],
  ['Search', 'Buscar'], ['Workspace', 'Espacio de trabajo'], ['Import', 'Importar'], ['Export', 'Exportar'], ['Validation', 'Validación'],
  ['Undo', 'Deshacer'], ['Redo', 'Rehacer'], ['Focus', 'Enfocar'], ['Previous', 'Anterior'], ['Next', 'Siguiente'], ['Toggle', 'Alternar'],
  ['Character', 'Personaje'], ['Level', 'Nivel'], ['rank', 'rango'], ['level', 'nivel'], ['Active', 'Activa'],
  ['Reset', 'Restablecer'], ['Delete', 'Eliminar'], ['RESHUFFLE', 'REORDENAR'], ['Lock order', 'Bloquear el orden'],
  ['Reshuffle', 'Reordenar'], ['reshuffling', 'reordenación de'], ['Select', 'Seleccionar'], ['System', 'Sistema'],
  ['Body', 'Cuerpo celeste'], ['Solar', 'Solar'], ['Wind', 'Eólica'], ['Biomes', 'Biomas'], ['biome', 'bioma'], ['biomes', 'biomas'],
  ['Very Poor', 'Muy deficiente'], ['V.Poor', 'M. def.'], ['Poor', 'Deficiente'], ['Normal', 'Normal'], ['Good', 'Buena'],
  ['None', 'Ninguna'], ['Unknown', 'Desconocido'], ['output', 'producción'], ['no modifier', 'sin modificador'],
  ['Item', 'Elemento'], ['Source', 'Origen'], ['Present', 'Presencia'], ['Producing', 'En producción'],
  ['Inputs', 'Materiales de entrada'], ['Logistics', 'Logística'], ['Inorganic', 'Inorgánico'], ['Organic', 'Orgánico'],
  ['Manufacturing', 'Fabricación'], ['Imports', 'Importaciones'], ['Exports', 'Exportaciones'], ['Unspecified', 'Sin especificar'],
  ['No local resources have been selected', 'No se han seleccionado recursos locales'], ['No manufacturing recorded', 'No hay fabricación registrada'],
  ['No imports', 'No hay importaciones'], ['No exports', 'No hay exportaciones'], ['No planned supply', 'No hay suministro planificado'],
  ['active', 'activo'], ['inactive', 'inactivo'], ['Destination', 'Destino'], ['Unlinked', 'Sin vincular'], ['unlinked', 'sin vincular'],
  ['linked to', 'vinculado a'], ['Linked to', 'Vinculado a'], ['nothing', 'nada'], ['No items available to export', 'No hay elementos disponibles para exportar'],
  ['No outbound cargo', 'No hay carga saliente'], ['No inbound cargo', 'No hay carga entrante'], ['Standard', 'Estándar'],
  ['All', 'Todo'], ['Errors', 'Errores'], ['Warnings', 'Advertencias'], ['Warning', 'Advertencia'], ['Error', 'Error'], ['Info', 'Información'],
  ['Open', 'Abrir'], ['issues', 'incidencias'], ['issue', 'incidencia'], ['errors', 'errores'], ['warnings', 'advertencias'],
  ['requires', 'necesita'], ['recorded', 'registrado'], ['missing', 'ausente'], ['Selected file', 'El archivo seleccionado'],
  ['selected file', 'archivo seleccionado'], ['selected collection', 'colección seleccionada'], ['Browser storage', 'El almacenamiento del navegador'],
  ['Changes', 'Los cambios'], ['Dismiss', 'Descartar'], ['Exported', 'Se ha exportado'], ['Imported', 'Se ha importado'],
  ['Import failed for', 'Error al importar'], ['does not contain', 'no contiene'], ['contains', 'contiene'], ['invalid', 'no válido'],
  ['Unsupported', 'No compatible'], ['Nothing to undo', 'Nada que deshacer'], ['Nothing to redo', 'Nada que rehacer'],
  ['Rename', 'Cambiar el nombre de'], ['Clear', 'Borrar'], ['Set', 'Establecer'], ['Change', 'Cambiar'],
  ['Start producing', 'Empezar a producir'], ['Stop producing', 'Dejar de producir'], ['Available from', 'Disponible en'],
  ['available', 'disponible'], ['selected', 'seleccionado'], ['Resource', 'Recurso'], ['Product', 'Producto'], ['resource', 'recurso'], ['product', 'producto'],
  ['Search for', 'Buscar'], ['Type an item name', 'Escribe el nombre de un elemento'], ['was found at', 'se ha encontrado en'],
  ['was not found at any', 'no se ha encontrado en ningún'], ['Missing Inputs', 'Faltan materiales'], ['Importing', 'Importando'], ['Exporting', 'Exportando'],
])
