import { buildReviewDraft } from './buildDraft.ts'

/** Independent Codex draft used by the French semantic review package. */
export const frFRReviewDraft = buildReviewDraft({
  'outpost.system.select': 'Sélectionner…',
  'outpost.body.select': 'Sélectionner…',
  "validation.activeProductionOrganicInvalidMany": "{resource} est marqué comme produit, mais ce producteur n’est pas éligible à la production organique sur cette planète.",
  "validation.activeProductionOrganicInvalidOne": "{resource} est marqué comme produit, mais ce producteur n’est pas éligible à la production organique sur cette planète.",
  "validation.activeProductionOrganicInvalid": "{resource} est marqué comme produit, mais ce producteur n’est pas éligible à la production organique sur cette planète.",
  "help.organic.unavailableBiomes": "{resource} n’est pas disponible auprès de cette espèce domesticable sur cette planète.",
  "help.organic.unavailableBiome": "{resource} n’est pas disponible auprès de cette espèce domesticable sur cette planète.",
  "help.organic.unavailablePlanet": "{resource} n’est pas disponible auprès de cette espèce domesticable sur cette planète.",
  "help.organic.availableBiomes": "{resource} est disponible auprès d’une espèce domesticable sur cette planète.",
  "help.organic.availableSelectedBiome": "{resource} est disponible auprès d’une espèce domesticable sur cette planète.",
  "help.organic.availableBiome": "{resource} est disponible auprès d’une espèce domesticable sur cette planète.",
  "help.organic.availablePlanet": "{resource} est disponible auprès d’une espèce domesticable sur cette planète.",
  "help.biomes": "Les biomes sélectionnés limitent la disponibilité des ressources inorganiques à celles qui peuvent s’y trouver.",
  "about.version": "Version {version}",
  "about.build": "Compilation {commit}",
  "about.modified": "locale / modifiée",
  "about.unknown": "locale / non vérifiée",
  "about.licenseSummary": "Code créé pour le projet : GPL-3.0-or-later, sans garantie. Les illustrations et le contenu issu du jeu relèvent de droits distincts.",
  "about.license": "Licence complète",
  "about.notices": "Mentions des tiers",
  "about.repository": "Dépôt du code source",
  "about.buildSource": "Source de cette compilation",
  "about.issues": "Bugs et suggestions",
  "about.contact": "Contact privé / alternatif",
  "about.support": "Soutenir Gooberpede",
  "about.funding": "Soutien volontaire au travail du développeur sur les mods et outils Bethesda. Les projets publiés sont gratuits ; les pourboires ou abonnements ne donnent droit à aucune fonctionnalité supplémentaire, exclusivité, accès, assistance prioritaire ou garantie de livraison.",
  "about.backup": "Enregistrement dans ce profil de navigateur sur ce site, sans synchronisation de compte ni sauvegarde sur serveur. Exportez avant d’effacer les données du navigateur ou de changer d’appareil. L’importation remplace la collection. Si l’enregistrement échoue, exportez votre travail en mémoire.",
  "about.unofficial": "Projet indépendant et non officiel, sans affiliation ni approbation de Bethesda Game Studios ou Microsoft.",
  "about.artwork": "Illustration du favicon (licence distincte) :",
  'about.attribution': 'designed by gravisio from Flaticon',
  'referenceFatal.explanation': 'Les données de référence requises n’ont pas pu être chargées correctement. Le tracker s’est arrêté afin de protéger votre travail enregistré.',
  'referenceFatal.privacy': 'Le signalement ouvre votre application de messagerie et contient uniquement des diagnostics techniques. Aucune donnée de réseau enregistrée n’est incluse automatiquement.',
  'shortcuts.introduction': 'Commandes globales disponibles dans toute l’application. Les raccourcis laissent la priorité à la saisie de texte et aux boîtes de dialogue ouvertes, le cas échéant.',
  'character.level.rejectedRestored': 'Niveau incorrect. La valeur {value} a été restaurée. Saisissez un niveau compris entre 1 et 999.',
  'character.level.rejectedEmpty': 'Niveau incorrect. La valeur précédente a été restaurée. Saisissez un niveau compris entre 1 et 999.',
  'character.skillRank.rejectedRestored': 'Rang incorrect. La valeur {value} a été restaurée. Saisissez un rang compris entre 0 et 4.',
  'character.skillRank.rejectedEmpty': 'Rang incorrect. La valeur précédente a été restaurée. Saisissez un rang compris entre 0 et 4.',
  'network.reset.explanation': 'Réinitialiser le réseau actuel avec un nouvel état par défaut ?',
  'network.delete.explanation': 'Supprimer le réseau actuel de cette collection ?',
  'network.delete.undoHint': 'Vous pouvez annuler cette action pendant la session actuelle.',
  'matrix.column.present': 'Présence',
  'matrix.column.producing': 'En production',
  'matrix.column.inputs': 'Intrants',
  'matrix.column.logistics': 'Logistique',
  'plannedSupply.heading': 'Approvisionnement planifié',
  'cargo.pad.semanticSummary': 'Destination : {destination}. Sortant : {outbound}. Entrant : {inbound}. {linkType}.',
  'cargo.pad.count': '{count} {count, plural, one {liaison} other {liaisons}}',
  'validation.manufacturingInputUnavailable': '{product} nécessite {input}, mais {input} n’est pas disponible dans cet avant-poste.',
  'validation.plannedSupplyUnresolved': '{count} {count, plural, one {élément} other {éléments}} dans l’approvisionnement planifié : {itemList}.',
  'validation.issueCount': 'Validation : {count} {count, plural, one {problème} other {problèmes}}',
  'validation.remediation.extraction': 'Extraction possible dans : {biomes}',
  "validation.remediation.harvesting": "Choisissez un producteur domesticable valide sur cette planète.",
  'validation.unresolvedCargoExport': 'Cette exportation de fret ne possède aucune source réelle.',
  'referenceFatal.diagnostic.asset': 'Fichier',
  'referenceFatal.reason.assetContentType': 'Un fichier de référence requis a été fourni avec un type de contenu incorrect.',
  'referenceFatal.reason.assetHash': 'Un fichier de référence requis ne correspond pas au manifeste.',
  'referenceFatal.reason.assetSize': 'Un fichier de référence requis dépasse la taille maximale.',
  'referenceFatal.reason.manifestVersion': 'La version du manifeste de référence n’est pas prise en charge.',
  'status.import.fileTooLarge': 'Cette importation est trop volumineuse pour être ouverte en toute sécurité.',
  'history.editManufacturing': 'Modifier la fabrication dans {outpost}',
  'history.unlinkCargoPad': 'Dissocier {outpost} / {pad}',
  'history.linkCargoPad': 'Relier {localOutpost} / {localPad} à {remoteOutpost} / {remotePad}',
  'matrix.tooltip.export.inactive': '{item} n’est pas exporté.',
  'validation.bodySystemMismatch': 'Le corps céleste sélectionné pour cet avant-poste n’appartient pas au système stellaire sélectionné.',
  'validation.interstellarHelium3': 'Cette liaison intersystème transporte du fret, mais son avant-poste ne dispose d’aucun approvisionnement en hélium-3.',
  'validation.missingCargoEndpoint': 'Cette connexion de fret fait référence à un avant-poste ou à une extrémité de liaison manquants.',
  'validation.characterNameLength': 'Les noms de personnage dans Starfield comportent normalement jusqu’à 25 caractères.',
  'validation.outpostNameLength': 'Starfield limite normalement les noms d’avant-poste à 25 caractères ; les noms plus longs ajoutés par des mods restent pris en charge.',
  'validation.regularPadCrossSystem': 'Cette liaison est connectée à un avant-poste situé dans un autre système stellaire ; utilisez plutôt une liaison intersystème.',
  'status.storage.recovery': 'Les données enregistrées dans le navigateur n’ont pas pu être restaurées. Une collection temporaire est utilisée ; l’original est conservé jusqu’à la prochaine modification.',
  'status.storage.unavailable': 'Le stockage du navigateur est indisponible. Cette collection est uniquement conservée en mémoire.',
  'status.storage.unsaved': 'Les modifications sont uniquement en mémoire et n’ont pas été enregistrées dans ce navigateur.',
  'status.storage.capacity': 'Cette collection est trop volumineuse pour être enregistrée en toute sécurité. Les modifications restent en mémoire.',
  'help.plannedSupply': 'Les éléments sélectionnés servent d’indicateurs jusqu’à ce qu’un approvisionnement local ou importé soit établi.',
  'help.logistics': 'Les éléments actuellement affectés à des liaisons sont affichés ici.',
  'help.present': 'Indique si une ressource peut être présente dans cet avant-poste.',
  'help.producing': 'Indique si cet avant-poste est actuellement configuré pour produire la ressource ou le produit.',
  'help.validation': 'Les erreurs signalent les états incorrects, les avertissements les états incomplets ou incohérents, et les informations les actions de suivi utiles.',
  'search.input.description': 'Saisissez le nom ou l’abréviation d’un élément, puis confirmez l’élément à rechercher.',
  'search.results.dragInstructions': 'Déplacez les résultats de recherche avec les touches fléchées. Maintenez Shift pour effectuer des déplacements plus importants.',
}, [
  ['Reference data unavailable', 'Données de référence indisponibles'], ['Reference data', 'Données de référence'],
  ['Required reference data', 'Données de référence requises'], ['reference data', 'données de référence'],
  ['could not be', 'n’a pas pu être'], ['could not', 'n’a pas pu'], ['Failed to load', 'Échec du chargement des'],
  ['Keyboard Shortcuts', 'Raccourcis clavier'], ['keyboard shortcuts', 'raccourcis clavier'],
  ['Resource Matrix', 'Matrice des ressources'], ['Planned Supply', 'Approvisionnement planifié'],
  ['Inter-System Cargo Links', 'Liaisons intersystème'], ['Inter-System Cargo Link', 'Liaison intersystème'],
  ['Cargo Links', 'Liaisons'], ['Cargo Link', 'Liaison'], ['cargo links', 'liaisons'], ['cargo link', 'liaison'],
  ['Outpost Management', "Gestion d’avant-poste"], ['Outpost Engineering', 'Ingénierie avant-poste'],
  ['Planetary Habitation', 'Habitat planétaire'], ['Research Methods', 'Méthodologie'], ['Special Projects', 'Projets spéciaux'],
  ['Active Production', 'Production active'], ['Search Results', 'Résultats de recherche'], ['Outpost Details', 'Détails de l’avant-poste'],
  ['outpost navigation', 'navigation des avant-postes'], ['Outpost Navigation', 'Navigation des avant-postes'],
  ['Manufactured Products', 'Produits manufacturés'], ['manufactured product', 'produit manufacturé'],
  ['Inorganic Resources', 'Ressources inorganiques'], ['Organic Resources', 'Ressources organiques'],
  ['No validation issues', 'Aucun problème de validation'], ['validation details', 'détails de validation'],
  ['star system', 'système stellaire'], ['planetary body', 'corps céleste'], ['local resources', 'ressources locales'],
  ['active production', 'production active'], ['explicit resource presence', 'présence explicite de ressources'],
  ['manufacturing list', 'liste de fabrication'], ['outbound items', 'éléments sortants'],
  ['available for extraction', 'disponible pour l’extraction'], ['available for harvesting', 'disponible pour la récolte'],
  ['not available', 'indisponible'], ['is available', 'est disponible'], ['is being produced', 'est en cours de production'],
  ['is not being produced', 'n’est pas en cours de production'], ['is being exported', 'est exporté'], ['is being imported', 'est importé'],
  ['Add items to', 'Ajouter des éléments à'], ['Remove all', 'Tout supprimer de'], ['Add product', 'Ajouter un produit'],
  ['Add outpost', 'Ajouter un avant-poste'], ['Delete Outpost', 'Supprimer l’avant-poste'], ['New Outpost', 'Nouvel avant-poste'],
  ['outposts', 'avant-postes'], ['outpost', 'avant-poste'], ['Outposts', 'Avant-postes'], ['Outpost', 'Avant-poste'],
  ['NETWORK', 'RÉSEAU'], ['Network', 'Réseau'], ['network', 'réseau'], ['collection', 'collection'],
  ['Language and region', 'Langue et région'], ['Automatic', 'Automatique'], ['Locale', 'Paramètres régionaux'],
  ['Reload', 'Recharger'], ['Report', 'Signaler'], ['Error code', 'Code d’erreur'], ['HTTP status', 'État HTTP'],
  ['Media type', 'Type de média'], ['Manifest schema version', 'Version du schéma du manifeste'],
  ['Expected dataset ID', 'ID attendu du jeu de données'], ['Actual dataset ID', 'ID réel du jeu de données'],
  ['Expected hash prefix', 'Préfixe de hachage attendu'], ['Actual hash prefix', 'Préfixe de hachage réel'],
  ['About', 'À propos'], ['Help', 'Aide'], ['Close', 'Fermer'], ['Cancel', 'Annuler'], ['cancel', 'annuler'],
  ['save', 'enregistrer'], ['edit', 'modifier'], ['Add', 'Ajouter'], ['Remove', 'Supprimer'], ['Move', 'Déplacer'],
  ['Drag', 'Faire glisser'], ['Expand', 'Développer'], ['Collapse', 'Réduire'], ['Show', 'Afficher'], ['Hide', 'Masquer'],
  ['History', 'Historique'], ['Search', 'Recherche'], ['Workspace', 'Espace de travail'], ['Import', 'Importer'], ['Export', 'Exporter'],
  ['Validation', 'Validation'], ['Undo', 'Annuler'], ['Redo', 'Rétablir'], ['Focus', 'Placer le focus sur'],
  ['Previous', 'Précédent'], ['Next', 'Suivant'], ['Toggle', 'Basculer'], ['details', 'détails'], ['Navigation', 'Navigation'],
  ['Character', 'Personnage'], ['Level', 'Niveau'], ['rank', 'rang'], ['level', 'niveau'],
  ['Active', 'Actif'], ['Reset', 'Réinitialiser'], ['Delete', 'Supprimer'], ['RESHUFFLE', 'RÉORGANISER'],
  ['Lock order', 'Verrouiller l’ordre'], ['Reshuffle', 'Réorganiser'], ['reshuffling', 'réorganisation de'],
  ['Select', 'Sélectionner'], ['System', 'Système'], ['Body', 'Corps céleste'], ['Solar', 'Solaire'], ['Wind', 'Vent'], ['Biomes', 'Biomes'],
  ['Very Poor', 'Très faible'], ['V.Poor', 'T. faible'], ['Poor', 'Faible'], ['Normal', 'Normal'], ['Good', 'Bon'], ['None', 'Aucun'], ['Unknown', 'Inconnu'],
  ['output', 'production'], ['no modifier', 'sans modificateur'], ['Item', 'Élément'], ['Source', 'Source'], ['Present', 'Présence'],
  ['Producing', 'En production'], ['Inputs', 'Intrants'], ['Logistics', 'Logistique'], ['Inorganic', 'Inorganique'], ['Organic', 'Organique'],
  ['Manufacturing', 'Fabrication'], ['Imports', 'Importations'], ['Exports', 'Exportations'], ['Unspecified', 'Non spécifié'],
  ['No local resources have been selected', 'Aucune ressource locale n’a été sélectionnée'], ['No manufacturing recorded', 'Aucune fabrication enregistrée'],
  ['No imports', 'Aucune importation'], ['No exports', 'Aucune exportation'], ['No planned supply', 'Aucun approvisionnement planifié'],
  ['active', 'actif'], ['inactive', 'inactif'], ['Destination', 'Destination'], ['Unlinked', 'Non liée'], ['unlinked', 'non liée'],
  ['linked to', 'liée à'], ['Linked to', 'Liée à'], ['Unknown', 'Inconnue'], ['nothing', 'rien'],
  ['No items available to export', 'Aucun élément disponible à exporter'], ['No outbound cargo', 'Aucun fret sortant'], ['No inbound cargo', 'Aucun fret entrant'],
  ['Standard', 'Standard'], ['All', 'Tous'], ['Errors', 'Erreurs'], ['Warnings', 'Avertissements'], ['Warning', 'Avertissement'], ['Error', 'Erreur'], ['Info', 'Information'],
  ['Open', 'Ouvrir'], ['issues', 'problèmes'], ['issue', 'problème'], ['errors', 'erreurs'], ['warnings', 'avertissements'],
  ['requires', 'nécessite'], ['recorded', 'enregistré'], ['missing', 'manquant'], ['unknown', 'inconnu'], ['appears more than once', 'apparaît plusieurs fois'],
  ['Selected file', 'Fichier sélectionné'], ['selected file', 'fichier sélectionné'], ['selected collection', 'collection sélectionnée'],
  ['Browser storage', 'Le stockage du navigateur'], ['Changes', 'Les modifications'], ['Dismiss', 'Fermer'], ['Exported', 'Exporté'], ['Imported', 'Importé'],
  ['Import failed for', 'Échec de l’importation de'], ['does not contain', 'ne contient pas'], ['contains', 'contient'], ['invalid', 'incorrect'], ['Unsupported', 'Non prise en charge :'],
  ['Nothing to undo', 'Rien à annuler'], ['Nothing to redo', 'Rien à rétablir'], ['Rename', 'Renommer'], ['Clear', 'Effacer'], ['Set', 'Définir'], ['Change', 'Modifier'],
  ['Start producing', 'Commencer la production de'], ['Stop producing', 'Arrêter la production de'],
  ['Available from', 'Disponible auprès de'], ['available', 'disponible'], ['selected', 'sélectionné'], ['Resource', 'Ressource'], ['Product', 'Produit'], ['resource', 'ressource'], ['product', 'produit'],
  ['Search for', 'Rechercher'], ['Type an item name', 'Saisissez le nom d’un élément'], ['was found at', 'a été trouvé dans'], ['was not found at any', 'n’a été trouvé dans aucun'],
  ['Missing Inputs', 'Intrants manquants'], ['Importing', 'Importation'], ['Exporting', 'Exportation'],
])
