import { buildReviewDraft } from './buildDraft.ts'

/** Independent Italian Codex draft used only by the semantic review package. */
export const itITReviewDraft = buildReviewDraft({
  "about.version": "Versione {version}",
  "about.build": "Compilazione {commit}",
  "about.modified": "locale / modificata",
  "about.unknown": "locale / non verificata",
  "about.licenseSummary": "Codice creato per il progetto: GPL-3.0-or-later, senza garanzia. La grafica e i contenuti derivati dal gioco sono soggetti a diritti distinti.",
  "about.license": "Licenza completa",
  "about.notices": "Note di terze parti",
  "about.repository": "Archivio del codice sorgente",
  "about.buildSource": "Sorgente di questa compilazione",
  "about.issues": "Errori e suggerimenti",
  "about.contact": "Contatto privato / alternativo",
  "about.support": "Sostieni Gooberpede",
  "about.funding": "Sostegno volontario al lavoro dello sviluppatore su mod e strumenti Bethesda. I progetti pubblicati sono gratuiti; mance o abbonamenti non acquistano funzioni aggiuntive, esclusive, accesso, assistenza prioritaria o impegni di consegna.",
  "about.backup": "Salvataggio in questo profilo del browser su questo sito, senza sincronizzazione dell’account né backup sul server. Esporta prima di cancellare i dati del browser o cambiare dispositivo. L’importazione sostituisce la raccolta. Se il salvataggio fallisce, esporta il lavoro in memoria.",
  "about.unofficial": "Progetto indipendente e non ufficiale, non affiliato né approvato da Bethesda Game Studios o Microsoft.",
  "about.artwork": "Grafica dell’icona del sito (licenza distinta):",
  'about.attribution': 'designed by gravisio from Flaticon',
  'referenceFatal.explanation': 'Non è stato possibile caricare correttamente i dati di riferimento richiesti. L’applicazione si è arrestata per proteggere il lavoro salvato.',
  'referenceFatal.privacy': 'La segnalazione apre l’app di posta elettronica e include solo dati diagnostici tecnici. I dati di rete salvati non vengono inclusi automaticamente.',
  'shortcuts.introduction': 'Comandi globali disponibili in tutta l’applicazione. Le scorciatoie lasciano la precedenza alla modifica del testo e alle finestre di dialogo aperte quando necessario.',
  'character.level.rejectedRestored': 'Livello non valido. È stato ripristinato {value}. Inserisci un livello da 1 a 999.',
  'character.level.rejectedEmpty': 'Livello non valido. È stato ripristinato il valore precedente. Inserisci un livello da 1 a 999.',
  'character.skillRank.rejectedRestored': 'Grado non valido. È stato ripristinato {value}. Inserisci un grado da 0 a 4.',
  'character.skillRank.rejectedEmpty': 'Grado non valido. È stato ripristinato il valore precedente. Inserisci un grado da 0 a 4.',
  'network.reset.explanation': 'Ripristinare la rete corrente a un nuovo stato predefinito?',
  'network.delete.explanation': 'Rimuovere la rete corrente da questa raccolta?',
  'network.delete.undoHint': 'Puoi annullare questa azione durante la sessione corrente.',
  'matrix.column.present': 'Presenza',
  'matrix.column.producing': 'In produzione',
  'matrix.column.inputs': 'Materiali richiesti',
  'matrix.column.logistics': 'Logistica',
  'plannedSupply.heading': 'Fornitura pianificata',
  'cargo.pad.semanticSummary': 'Destinazione: {destination}. In uscita: {outbound}. In entrata: {inbound}. {linkType}.',
  'cargo.pad.count': '{count} {count, plural, one {collegamento merci} other {collegamenti merci}}',
  'validation.issueCount': 'Convalida: {count} {count, plural, one {problema} other {problemi}}',
  'validation.manufacturingInputUnavailable': '{product} richiede {input}, ma {input} non è disponibile in questo avamposto.',
  'validation.plannedSupplyUnresolved': '{count} {count, plural, one {elemento} other {elementi}} in Fornitura pianificata: {itemList}.',
  'validation.activeProductionOrganicInvalid': '{resource} risulta in produzione, ma non può essere raccolta nell’avamposto in {biomes}.',
  'validation.activeProductionInorganicInvalid': '{resource} risulta in produzione, ma non può essere estratta nell’avamposto in {biomes}.',
  'validation.activeProductionOrganicInvalidOne': '{resource} risulta in produzione, ma non può essere raccolta nell’avamposto nel bioma {biomes}.',
  'validation.activeProductionOrganicInvalidMany': '{resource} risulta in produzione, ma non può essere raccolta nell’avamposto nei biomi {biomes}.',
  'validation.activeProductionInorganicInvalidOne': '{resource} risulta in produzione, ma non può essere estratta nell’avamposto nel bioma {biomes}.',
  'validation.activeProductionInorganicInvalidMany': '{resource} risulta in produzione, ma non può essere estratta nell’avamposto nei biomi {biomes}.',
  'validation.bodySystemMismatch': 'Il corpo celeste selezionato per questo avamposto non appartiene al sistema stellare selezionato.',
  'validation.cargoPadLinkedMultiple': 'Questo collegamento merci ha più di una connessione.',
  'validation.cargoPadSkillLimit': 'Questo avamposto ha {count} collegamenti merci, ma il livello attuale di {skill} ne consente al massimo {limit}.',
  'validation.duplicateOutpostName': '{count} avamposti si chiamano «{name}». Si consigliano nomi univoci per evitare ambiguità.',
  'validation.interstellarHelium3': 'Questo collegamento merci intersistema invia merci, ma il suo avamposto non dispone di una fornitura di elio-3.',
  'validation.invalidCharacterLevel': 'Il livello del personaggio è {level}, ma un livello registrato deve essere un numero intero da {minimum} a {maximum}.',
  'validation.invalidSkillLevel': '{skill} è al livello {level}, ma i livelli validi sono numeri interi da {minimum} a {maximum}.',
  'validation.missingCargoEndpoint': 'Questa connessione merci fa riferimento a un avamposto o a un’estremità di collegamento merci mancante.',
  'validation.organicInputUnavailable': '{species} richiede {input}, ma {input} non è disponibile in questo avamposto.',
  'validation.outpostBodyNotEligible': 'Questo avamposto si trova su un corpo celeste che non può ospitare avamposti.',
  'validation.characterNameLength': 'I nomi dei personaggi in Starfield usano normalmente fino a 25 caratteri.',
  'validation.outpostNameLength': 'Starfield limita normalmente i nomi degli avamposti a 25 caratteri; i nomi più lunghi aggiunti dalle mod restano supportati.',
  'validation.outpostSkillLimit': 'Questa rete contiene {count} avamposti, ma il livello attuale di {skill} ne consente al massimo {limit}.',
  'validation.planetaryHabitationRequirement': 'Questo avamposto richiede il grado {required} di {skill}, ma il grado del personaggio registrato è {recorded}.',
  'validation.regularPadCrossSystem': 'Questo collegamento merci è connesso a un avamposto in un altro sistema stellare; usa invece un collegamento merci intersistema.',
  'validation.selectedBiomeInvalid': 'Il bioma selezionato appartiene a un altro corpo celeste.',
  'validation.selfLinkedCargoPad': 'Questa connessione merci usa lo stesso collegamento merci a entrambe le estremità.',
  'validation.unspecifiedOrganicSource': '{resource} risulta in produzione, ma non è stata specificata alcuna origine di flora o fauna.',
  'validation.unresolvedCargoExport': 'Questa esportazione di merci non ha un’origine effettiva.',
  'validation.xTechCapabilityProduced': '{resource} risulta in produzione, ma il personaggio non dispone della capacità di estrazione richiesta.',
  'validation.xTechCapabilityPresent': '{resource} risulta presente, ma il personaggio non dispone della capacità di estrazione richiesta.',
  'validation.xTechRequiresPresence': '{resource} risulta in produzione, ma non è registrata esplicitamente come presente in questo avamposto.',
  'validation.remediation.extraction': 'Disponibile per l’estrazione in: {biomes}',
  'validation.remediation.harvesting': 'Disponibile per la raccolta in: {biomes}',
  'validation.remediation.organicSources': 'Disponibile da: {sources}',
  'status.storage.recovery': 'Non è stato possibile ripristinare i dati salvati nel browser. Viene usata una raccolta temporanea; l’originale resta conservato fino a una modifica.',
  'status.storage.unavailable': 'Lo spazio di archiviazione del browser non è disponibile. Questa raccolta è solo in memoria.',
  'status.storage.unsaved': 'Le modifiche sono solo in memoria e non sono state salvate in questo browser.',
  'status.storage.capacity': 'Questa raccolta è troppo grande per essere salvata in sicurezza. Le modifiche restano in memoria.',
  'status.referenceData.loaded': 'Dati di riferimento caricati: {systems} sistemi, {bodies} corpi celesti, {resources} risorse e {products} prodotti.',
  'help.plannedSupply': 'Gli elementi selezionati fungono da segnaposto finché non viene stabilita una fornitura locale o importata.',
  'help.logistics': 'Qui sono mostrati gli elementi attualmente assegnati ai collegamenti merci.',
  'help.biomes': 'I biomi selezionati limitano la disponibilità alle risorse che possono comparire in tali biomi.',
  'help.present': 'Indica se una risorsa può essere presente in questo avamposto.',
  'help.producing': 'Indica se questo avamposto è attualmente configurato per produrre la risorsa o il prodotto.',
  'help.interSystem': 'I collegamenti merci intersistema possono connettere avamposti in sistemi stellari diversi e richiedono elio-3.',
  'help.validation': 'Gli errori indicano stati non validi, gli avvisi stati incompleti o incoerenti e le informazioni evidenziano utili azioni successive.',
  'search.input.description': 'Digita il nome o l’abbreviazione di un elemento, quindi conferma l’elemento da cercare.',
  'search.results.dragInstructions': 'Sposta i risultati di ricerca con i tasti freccia. Tieni premuto Shift per spostamenti più ampi.',
  'referenceFatal.report.body': 'L’applicazione si è arrestata durante la verifica dei dati di riferimento. Diagnostica tecnica:',
  'referenceFatal.reason.manifestFetch': 'Non è stato possibile recuperare il manifesto dei dati di riferimento.',
  'referenceFatal.reason.manifestInvalid': 'Il manifesto dei dati di riferimento non è valido.',
  'referenceFatal.reason.manifestVersion': 'La versione del manifesto dei dati di riferimento non è supportata.',
  'referenceFatal.reason.buildMismatch': 'I dati di riferimento appartengono a una versione diversa dell’app.',
  'referenceFatal.reason.internal': 'Non è stato possibile completare il controllo di integrità dei dati di riferimento.',
  'common.moveUp': 'Sposta {item} in alto', 'common.moveDown': 'Sposta {item} in basso', 'common.dragToReorder': 'Trascina {item} per riordinare',
  'about.description': 'Uno strumento per registrare le reti di avamposti di Starfield.',
  'shortcuts.action.focusSearch': 'Attiva la ricerca di elementi',
  'outpost.name.label': 'Nome avamposto', 'outpost.system.select': 'Seleziona sistema...', 'outpost.body.select': 'Seleziona corpo celeste...',
  'outpost.referenceData.empty': 'Nessun dato di riferimento delle risorse trovato per questo corpo celeste.',
  'production.empty': 'Nessuna risorsa locale selezionata.',
  'matrix.action.togglePresent': 'Attiva/disattiva la presenza di {item}', 'matrix.action.toggleProducing': 'Attiva/disattiva la produzione di {item}',
  'matrix.action.toggleProducingSource': 'Attiva/disattiva la produzione di {item} da {source}',
  'plannedSupply.remove': 'Rimuovi {item} da Fornitura pianificata', 'plannedSupply.add': 'Aggiungi {item} a Fornitura pianificata',
  'cargo.export.toggle': 'Attiva/disattiva l’esportazione di {item}', 'cargo.destination.noPads': '{outpost} — nessun collegamento merci',
  'validation.duplicateLocalResource': '{item} compare più di una volta nelle risorse locali di questo avamposto.',
  'validation.duplicateActiveProduction': '{item} compare più di una volta nella produzione attiva di questo avamposto.',
  'validation.duplicateExplicitPresence': '{item} compare più di una volta nella presenza esplicita delle risorse di questo avamposto.',
  'validation.duplicateBiome': '{item} compare più di una volta nella selezione dei biomi di questo avamposto.',
  'validation.duplicateManufacturing': '{item} compare più di una volta nell’elenco di fabbricazione di questo avamposto.',
  'validation.duplicatePlannedSupply': '{item} compare più di una volta nella Fornitura pianificata di questo avamposto.',
  'validation.duplicateOutboundItem': '{item} compare più di una volta tra gli elementi in uscita di questo collegamento merci.',
  'validation.unknownSystem': 'Questo avamposto fa riferimento all’ID sistema stellare sconosciuto «{id}».',
  'validation.unknownBody': 'Questo avamposto fa riferimento all’ID corpo celeste sconosciuto «{id}».',
  'validation.unknownLocalResource': 'Questo avamposto fa riferimento all’ID risorsa sconosciuto «{id}» nelle risorse locali.',
  'validation.unknownBiome': 'Questo avamposto fa riferimento all’ID bioma del corpo sconosciuto «{id}».',
  'validation.unknownExplicitResource': 'Questo avamposto fa riferimento all’ID risorsa sconosciuto «{id}» nella presenza esplicita delle risorse.',
  'validation.unknownProductionResource': 'Questo avamposto fa riferimento all’ID risorsa sconosciuto «{id}» nella produzione attiva.',
  'validation.unknownProductionSpecies': 'Questo avamposto fa riferimento all’ID specie sconosciuto «{id}» nella produzione attiva.',
  'validation.unknownManufacturingProduct': 'Questo avamposto fa riferimento all’ID prodotto sconosciuto «{id}» nell’elenco di fabbricazione.',
  'validation.unknownPlannedItem': 'Questo avamposto fa riferimento all’ID {kind} sconosciuto «{id}» in Fornitura pianificata.',
  'validation.unknownOutboundItem': 'Questo collegamento merci fa riferimento all’ID {kind} sconosciuto «{id}» tra gli elementi in uscita.',
  'status.import.failed': 'Importazione di {fileName} non riuscita: {reason}', 'status.import.readFailed': 'Non è stato possibile leggere il file selezionato.',
  'status.import.invalid': 'Non è stato possibile importare il file selezionato.', 'status.import.invalidJson': 'Il file selezionato non contiene JSON valido.',
  'status.import.invalidCollection': 'Il file selezionato non è una raccolta di reti valida.', 'status.import.emptyCollection': 'La raccolta selezionata non contiene reti.',
  'status.import.malformedEntry': 'La raccolta selezionata contiene una voce di rete non valida.',
  'status.import.duplicateNetworkId': 'La raccolta selezionata contiene l’ID rete duplicato «{id}».',
  'status.import.invalidCharacter': 'Il file selezionato contiene dati del personaggio non validi.',
  'status.import.invalidCapabilities': 'Il file selezionato contiene dati sulle capacità del personaggio non validi.',
  'status.import.invalidSkills': 'Il file selezionato contiene dati sulle abilità del personaggio non validi.',
  'status.import.invalidNetwork': 'Il file selezionato non è una rete di avamposti valida.', 'status.import.invalidOutpost': 'Il file selezionato contiene un avamposto non valido.',
  'status.import.invalidExplicitPresence': 'Il file selezionato contiene dati di presenza esplicita delle risorse non validi.',
  'status.import.invalidCargoPad': 'Il file selezionato contiene un collegamento merci non valido.',
  'status.import.invalidStructure': 'Il file selezionato contiene dati di rete non validi.',
  'status.import.invalidIdentity': 'Il file selezionato contiene un identificatore stabile vuoto o duplicato.',
  'status.import.fileTooLarge': 'Questa importazione è troppo grande per essere aperta in sicurezza.',
  'status.import.arrayLimitExceeded': 'Questa importazione contiene troppi elementi in una sezione.',
  'status.import.tooManyNetworks': 'Questa importazione contiene troppe reti salvate.',
  'status.import.aggregateLimitExceeded': 'Questa importazione contiene troppi elementi per essere aperta in sicurezza.',
  'status.import.stringTooLong': 'Questa importazione contiene un valore di testo troppo lungo.',
  'status.referenceData.reload': 'Ricarica dati di riferimento', 'status.drag.reorder': 'Rilascia per riordinare · Esc per annullare',
  'transfer.import.tooltip': 'Importa tutte le reti da JSON',
  'history.unlinkCargoPad': 'Scollega {outpost} / {pad}', 'history.linkCargoPad': 'Collega {localOutpost} / {localPad} a {remoteOutpost} / {remotePad}',
  'history.changeCargoLink': 'Cambia il collegamento di {localOutpost} / {localPad} in {remoteOutpost} / {remotePad}',
  'history.renameCharacter': 'Rinomina il personaggio da {previousName} a {name}',
  'history.changeCharacterLevel': 'Cambia il livello del personaggio da {previousLevel} a {level}', 'history.changeSkill': 'Cambia {skill} da {previousRank} a {rank}',
  'history.moveOutpost': 'Sposta {outpost} alla posizione {position}', 'history.moveCargoPad': 'Sposta {outpost} / {pad} alla posizione {position}',
  'history.addExport': 'Aggiungi l’esportazione {item} a {outpost} / {pad}', 'history.removeExport': 'Rimuovi l’esportazione {item} da {outpost} / {pad}',
  'history.changeCargoPadType': 'Cambia {outpost} / {pad} in {type}', 'history.renameOutpost': 'Rinomina l’avamposto da {previousName} a {name}',
  'history.changeSystem': 'Cambia il sistema di {outpost} in {system}', 'history.clearSystem': 'Cancella il sistema di {outpost}',
  'history.changeBody': 'Cambia il corpo celeste di {outpost} in {body}', 'history.clearBody': 'Cancella il corpo celeste di {outpost}',
  'history.addBiome': 'Aggiungi una selezione di bioma a {outpost}', 'history.removeBiome': 'Rimuovi una selezione di bioma da {outpost}',
  'history.addLocalResource': 'Aggiungi la risorsa locale {resource} a {outpost}', 'history.removeLocalResource': 'Rimuovi la risorsa locale {resource} da {outpost}',
  'history.addExplicitResource': 'Aggiungi la risorsa esplicita {resource} a {outpost}', 'history.removeExplicitResource': 'Rimuovi la risorsa esplicita {resource} da {outpost}',
  'history.startProducing': 'Avvia la produzione di {resource} in {outpost}', 'history.stopProducing': 'Interrompi la produzione di {resource} in {outpost}',
  'history.editManufacturing': 'Modifica la fabbricazione in {outpost}',
  'help.forContext': 'Aiuto per {context}', 'help.contextLabel': 'Aiuto per {context}',
  'help.organic.unavailablePlanet': '{resource} non è disponibile da questa specie domesticabile su questo pianeta.',
  'help.organic.unavailableBiome': '{resource} non è disponibile da questa specie domesticabile nel bioma selezionato.',
  'help.organic.unavailableBiomes': '{resource} non è disponibile da questa specie domesticabile nei biomi selezionati.',
  'help.organic.availablePlanet': '{resource} è disponibile da una specie domesticabile su questo pianeta.',
  'help.organic.availableBiome': '{resource} è disponibile da una specie domesticabile in {biome}.',
  'help.organic.availableSelectedBiome': '{resource} è disponibile da una specie domesticabile nel bioma selezionato.',
  'help.organic.availableBiomes': '{resource} è disponibile da una specie domesticabile nei biomi selezionati.',
  'help.inorganicPresentRecorded': '{resource} risulta presente in questo avamposto.', 'help.inorganicPresentPossible': '{resource} potrebbe essere presente in questo avamposto.',
  'matrix.action.xTech.add': 'Aggiungi {resource} come presente',
  'matrix.tooltip.xTech.add': 'Aggiungi {resource} come presente. Può essere estratta in qualsiasi avamposto se sono disponibili nuclei energetici di X-Tech.',
  'matrix.tooltip.xTech.present': '{resource} è stata registrata esplicitamente come presente in questo avamposto.',
  'matrix.tooltip.producing.active': '{item} è in produzione in questo avamposto.', 'matrix.tooltip.producing.inactive': '{item} non è in produzione in questo avamposto.',
  'matrix.tooltip.manufacturing.blocked': '{item} non è in produzione in questo avamposto perché mancano i materiali richiesti.',
  'matrix.tooltip.input.available': '{item} è disponibile in questo avamposto.', 'matrix.tooltip.input.unavailable': '{item} non è disponibile in questo avamposto.',
  'matrix.tooltip.export.active': '{item} viene esportato a {destinations}.',
  'search.input.label': 'Cerca risorse o prodotti negli avamposti.', 'search.submit': 'Cerca elemento',
  'search.results.found': '{searchItem} è stato trovato in {count} {count, plural, one {avamposto} other {avamposti}}.',
  'referenceFatal.report.subject': 'Problema con i dati di riferimento dell’applicazione per avamposti di Starfield',
  'referenceFatal.diagnostic.schemaVersion': 'Versione dello schema del manifesto',
  'referenceFatal.reason.assetHash': 'Un file di riferimento richiesto non corrisponde al manifesto.',
  'about.closeDialog': 'Chiudi la finestra Informazioni', 'shortcuts.closeDialog': 'Chiudi la finestra Scorciatoie da tastiera',
  'shortcuts.action.focusSearchResults': 'Attiva i risultati di ricerca',
  'shortcuts.action.toggleNavigation': 'Mostra o nascondi la navigazione', 'shortcuts.action.focusNavigation': 'Attiva la navigazione',
  'shortcuts.action.focusOutpostDetails': 'Attiva i dettagli dell’avamposto', 'shortcuts.action.focusPlannedSupply': 'Attiva Fornitura pianificata',
  'shortcuts.action.focusResourceMatrix': 'Attiva Matrice delle risorse', 'shortcuts.action.focusCargoLinks': 'Attiva Collegamenti merci',
  'shortcuts.action.toggleValidation': 'Attiva/disattiva i dettagli della convalida',
  'network.reset.confirmTitle': 'RIPRISTINA RETE', 'network.delete.confirmTitle': 'ELIMINA RETE',
  'outpost.navigation.finishReshuffle': 'Termina il riordino degli avamposti', 'cargo.finishReshuffle': 'Termina il riordino dei collegamenti merci',
  'status.dismiss': 'Ignora il messaggio di stato',
  'status.import.unsupportedCollectionSchema': 'Versione dello schema della raccolta di reti non supportata: {version}',
  'status.import.unsupportedNetworkSchema': 'Versione dello schema di rete non supportata: {version}',
  'status.referenceData.failed': 'Caricamento dei dati di riferimento non riuscito.', 'status.referenceData.error': 'Errore dei dati di riferimento: {detail}',
  'transfer.export.tooltip': 'Esporta tutte le reti in JSON', 'history.importNetworks': 'Importa reti',
  'history.clearCharacterLevel': 'Cancella il livello del personaggio', 'history.setCharacterLevel': 'Imposta il livello del personaggio su {level}',
  'search.input.placeholder': 'Cerca risorse o prodotti', 'search.results.flag.missingInputs': 'Materiali richiesti mancanti',
  'outpost.navigation.addWithLimit': 'Aggiungi avamposto ({count} di {limit})',
  'cargo.expandAll': 'Espandi tutto', 'cargo.collapseAll': 'Comprimi tutto',
  'cargo.addWithLimit': 'Aggiungi collegamento merci ({count} di {limit})', 'history.setSkill': 'Imposta {skill} su {rank}',
  'cargo.interSystem.button': 'Intersistema',
}, [
  ['Reference data unavailable', 'Dati di riferimento non disponibili'], ['Required reference data', 'I dati di riferimento richiesti'],
  ['Reference data', 'Dati di riferimento'], ['reference data', 'dati di riferimento'], ['reference manifest', 'manifest dei dati di riferimento'],
  ['could not be retrieved', 'non è stato possibile recuperare'], ['could not complete', 'non è stato possibile completare'], ['is unsupported', 'non è supportato'],
  ['is invalid', 'non è valido'], ['belongs to a different app build', 'appartiene a una build diversa dell’app'],
  ['A required reference file', 'Un file di riferimento richiesto'], ['contains invalid JSON', 'contiene JSON non valido'],
  ['has an invalid structure', 'ha una struttura non valida'], ['exceeds the size limit', 'supera il limite di dimensione'],
  ['does not match the manifest', 'non corrisponde al manifest'], ['was served with the wrong content type', 'è stato fornito con un tipo di contenuto errato'],
  ['Language and region', 'Lingua e regione'], ['Automatic', 'Automatico'], ['Locale', 'Impostazioni locali'],
  ['Keyboard Shortcuts', 'Scorciatoie da tastiera'], ['Resource Matrix', 'Matrice delle risorse'], ['Planned Supply', 'Fornitura pianificata'],
  ['Active Production', 'Produzione attiva'], ['Inter-System Cargo Links', 'Collegamenti merci intersistema'],
  ['Inter-System Cargo Link', 'Collegamento merci intersistema'], ['Cargo Links', 'Collegamenti merci'], ['Cargo Link', 'Collegamento merci'],
  ['cargo links', 'collegamenti merci'], ['cargo link', 'collegamento merci'], ['Outpost Management', 'Gestione avamposto'],
  ['Outpost Engineering', 'Ingegneria avamposti'], ['Planetary Habitation', 'Insediamento planetario'],
  ['Research Methods', 'Metodi di ricerca'], ['Special Projects', 'Progetti speciali'],
  ['Outpost Navigation', 'Navigazione avamposti'], ['Outpost Details', 'Dettagli avamposto'], ['outpost navigation', 'navigazione avamposti'],
  ['Manufactured Products', 'Prodotti fabbricati'], ['Inorganic Resources', 'Risorse inorganiche'], ['Organic Resources', 'Risorse organiche'],
  ['Search Results', 'Risultati di ricerca'], ['No validation issues', 'Nessun problema di convalida'], ['validation details', 'dettagli della convalida'],
  ['star system', 'sistema stellare'], ['planetary body', 'corpo celeste'], ['local resources', 'risorse locali'],
  ['active production', 'produzione attiva'], ['explicit resource presence', 'presenza esplicita delle risorse'],
  ['manufacturing list', 'elenco di fabbricazione'], ['outbound items', 'elementi in uscita'],
  ['appears more than once in', 'compare più di una volta in'], ['refers to unknown', 'fa riferimento a un'], ['unknown', 'sconosciuto'],
  ['is recorded as produced', 'risulta in produzione'], ['is recorded as present', 'risulta presente'], ['is not available', 'non è disponibile'],
  ['is available', 'è disponibile'], ['is being produced', 'è in produzione'], ['is not being produced', 'non è in produzione'],
  ['is being exported', 'viene esportato'], ['is not being exported', 'non viene esportato'], ['is being imported', 'viene importato'],
  ['available for extraction', 'disponibile per l’estrazione'], ['available for harvesting', 'disponibile per la raccolta'],
  ['Add items to', 'Aggiungi elementi a'], ['Remove all', 'Rimuovi tutto da'], ['Add manufactured product', 'Aggiungi prodotto fabbricato'],
  ['Add product', 'Aggiungi prodotto'], ['Add outpost', 'Aggiungi avamposto'], ['Delete Outpost', 'Elimina avamposto'], ['New Outpost', 'Nuovo avamposto'],
  ['outposts', 'avamposti'], ['outpost', 'avamposto'], ['Outposts', 'Avamposti'], ['Outpost', 'Avamposto'],
  ['NETWORK', 'RETE'], ['Network', 'Rete'], ['network', 'rete'], ['collection', 'raccolta'],
  ['Reload', 'Ricarica'], ['Report', 'Segnala'], ['Error code', 'Codice di errore'], ['Asset', 'File'], ['HTTP status', 'Stato HTTP'],
  ['Media type', 'Tipo di contenuto'], ['Manifest schema version', 'Versione dello schema del manifest'], ['Expected dataset ID', 'ID previsto del set di dati'],
  ['Actual dataset ID', 'ID effettivo del set di dati'], ['Expected hash prefix', 'Prefisso hash previsto'], ['Actual hash prefix', 'Prefisso hash effettivo'],
  ['About', 'Informazioni'], ['Help', 'Aiuto'], ['Close', 'Chiudi'], ['Cancel', 'Annulla'], ['cancel', 'annullare'], ['save', 'salvare'], ['edit', 'modificare'],
  ['Add', 'Aggiungi'], ['Remove', 'Rimuovi'], ['Move', 'Sposta'], ['Drag', 'Trascina'], ['Expand', 'Espandi'], ['Collapse', 'Comprimi'],
  ['Show', 'Mostra'], ['Hide', 'Nascondi'], ['History', 'Cronologia'], ['Search', 'Cerca'], ['Workspace', 'Area di lavoro'],
  ['Import', 'Importa'], ['Export', 'Esporta'], ['Validation', 'Convalida'], ['Undo', 'Annulla'], ['Redo', 'Ripeti'],
  ['Focus', 'Porta il focus su'], ['Previous', 'Precedente'], ['Next', 'Successivo'], ['Toggle', 'Attiva/disattiva'],
  ['Character', 'Personaggio'], ['Level', 'Livello'], ['rank', 'grado'], ['level', 'livello'], ['Active', 'Attiva'],
  ['Reset', 'Ripristina'], ['Delete', 'Elimina'], ['RESHUFFLE', 'RIORDINA'], ['Lock order', "Blocca l'ordine"],
  ['Reshuffle', 'Riordina'], ['reshuffling', 'riordino di'], ['Select', 'Seleziona'], ['System', 'Sistema'], ['Body', 'Corpo celeste'],
  ['Solar', 'Solare'], ['Wind', 'Eolica'], ['Biomes', 'Biomi'], ['biome', 'bioma'], ['biomes', 'biomi'],
  ['Very Poor', 'Molto scarsa'], ['V.Poor', 'M. scarsa'], ['Poor', 'Scarsa'], ['Normal', 'Normale'], ['Good', 'Buona'], ['None', 'Nessuna'],
  ['Unknown', 'Sconosciuto'], ['output', 'produzione'], ['no modifier', 'senza modificatore'], ['Item', 'Elemento'], ['Source', 'Origine'],
  ['Present', 'Presenza'], ['Producing', 'In produzione'], ['Inputs', 'Materiali richiesti'], ['Logistics', 'Logistica'],
  ['Inorganic', 'Inorganico'], ['Organic', 'Organico'], ['Manufacturing', 'Fabbricazione'], ['Imports', 'Importazioni'], ['Exports', 'Esportazioni'],
  ['Unspecified', 'Non specificata'], ['No local resources have been selected', 'Nessuna risorsa locale selezionata'],
  ['No manufacturing recorded', 'Nessuna fabbricazione registrata'], ['No imports', 'Nessuna importazione'], ['No exports', 'Nessuna esportazione'],
  ['No planned supply', 'Nessuna fornitura pianificata'], ['active', 'attivo'], ['inactive', 'inattivo'], ['Destination', 'Destinazione'],
  ['Unlinked', 'Non collegato'], ['unlinked', 'non collegato'], ['linked to', 'collegato a'], ['Linked to', 'Collegato a'], ['nothing', 'niente'],
  ['No items available to export', 'Nessun elemento disponibile per l’esportazione'], ['No outbound cargo', 'Nessuna merce in uscita'],
  ['No inbound cargo', 'Nessuna merce in entrata'], ['Standard', 'Standard'], ['All', 'Tutti'], ['Errors', 'Errori'], ['Warnings', 'Avvisi'],
  ['Warning', 'Avviso'], ['Error', 'Errore'], ['Info', 'Informazione'], ['Open', 'Apri'], ['issues', 'problemi'], ['issue', 'problema'],
  ['errors', 'errori'], ['warnings', 'avvisi'], ['requires', 'richiede'], ['recorded', 'registrato'], ['missing', 'mancante'],
  ['Selected file', 'Il file selezionato'], ['selected file', 'file selezionato'], ['selected collection', 'raccolta selezionata'],
  ['Browser storage', 'Lo spazio di archiviazione del browser'], ['Changes', 'Le modifiche'], ['Dismiss', 'Ignora'],
  ['Exported', 'Esportato'], ['Imported', 'Importato'], ['Import failed for', 'Importazione non riuscita per'], ['does not contain', 'non contiene'],
  ['contains', 'contiene'], ['invalid', 'non valido'], ['Unsupported', 'Non supportata'], ['Nothing to undo', 'Niente da annullare'],
  ['Nothing to redo', 'Niente da ripetere'], ['Rename', 'Rinomina'], ['Clear', 'Cancella'], ['Set', 'Imposta'], ['Change', 'Cambia'],
  ['Start producing', 'Avvia la produzione di'], ['Stop producing', 'Interrompi la produzione di'], ['Available from', 'Disponibile da'],
  ['available', 'disponibile'], ['selected', 'selezionato'], ['Resource', 'Risorsa'], ['Product', 'Prodotto'], ['resource', 'risorsa'], ['product', 'prodotto'],
  ['Search for', 'Cerca'], ['Type an item name', 'Digita il nome di un elemento'], ['was found at', 'è stato trovato in'],
  ['was not found at any', 'non è stato trovato in alcun'], ['Missing Inputs', 'Materiali mancanti'], ['Importing', 'Importazione'], ['Exporting', 'Esportazione'],
])
