/**
 * Purpose: Independent Polish semantic-review draft, kept outside the runtime catalogue.
 * Architecture: Exhaustive key-by-key editorial candidate consumed by review-package tooling only.
 * Change this file when: Polish semantic review corrects a draft wording before adjudication.
 */
import type { MessageCatalogue } from '../types.ts'

export const plPLReviewDraft = {
  "about.version": "Wersja {version}",
  "about.build": "Kompilacja {commit}",
  "about.modified": "lokalna / zmodyfikowana",
  "about.unknown": "lokalna / niezweryfikowana",
  "about.licenseSummary": "Kod autorski projektu: GPL-3.0-or-later, bez gwarancji. Grafiki i treści pochodzące z gry podlegają odrębnym prawom.",
  "about.license": "Pełna licencja",
  "about.notices": "Informacje o materiałach zewnętrznych",
  "about.repository": "Repozytorium kodu źródłowego",
  "about.buildSource": "Źródło tej kompilacji",
  "about.issues": "Błędy i sugestie",
  "about.contact": "Kontakt prywatny / alternatywny",
  "about.support": "Wesprzyj Gooberpede",
  "about.funding": "Dobrowolne wsparcie pracy autora nad modami i narzędziami do gier Bethesda. Opublikowane projekty są bezpłatne; napiwki ani członkostwo nie zapewniają dodatkowych funkcji, treści na wyłączność, dostępu, priorytetowej pomocy ani zobowiązań do dostarczenia prac.",
  "about.backup": "Zapis w tym profilu przeglądarki na tej stronie, bez synchronizacji konta ani kopii na serwerze. Eksportuj przed usunięciem danych przeglądarki lub zmianą urządzenia. Import zastępuje kolekcję. Jeśli zapis się nie powiedzie, wyeksportuj pracę z pamięci.",
  "about.unofficial": "Niezależny, nieoficjalny projekt, niepowiązany z Bethesda Game Studios ani Microsoft i niezatwierdzony przez te firmy.",
  "about.artwork": "Grafika ikony witryny (odrębna licencja):",
  'referenceFatal.heading': 'Dane referencyjne są niedostępne',
  'referenceFatal.explanation': 'Nie udało się poprawnie wczytać wymaganych danych referencyjnych. Działanie aplikacji zostało zatrzymane, aby chronić zapisane dane.',
  'referenceFatal.reload': 'Wczytaj ponownie',
  'referenceFatal.report': 'Zgłoś problem',
  'referenceFatal.privacy': 'Zgłoszenie otworzy aplikację pocztową i będzie zawierać wyłącznie diagnostykę techniczną. Dane zapisanych sieci nie zostaną dołączone automatycznie.',
  'referenceFatal.report.subject': 'Błąd danych referencyjnych narzędzia sieci placówek Starfield',
  'referenceFatal.report.body': 'Aplikacja została zatrzymana podczas weryfikacji danych referencyjnych. Diagnostyka techniczna:',
  'referenceFatal.diagnostic.code': 'Kod błędu',
  'referenceFatal.diagnostic.asset': 'Zasób',
  'referenceFatal.diagnostic.status': 'Status HTTP',
  'referenceFatal.diagnostic.mediaType': 'Typ multimediów',
  'referenceFatal.diagnostic.schemaVersion': 'Wersja schematu manifestu',
  'referenceFatal.diagnostic.expectedDataset': 'Oczekiwany ID zestawu danych',
  'referenceFatal.diagnostic.actualDataset': 'Rzeczywisty ID zestawu danych',
  'referenceFatal.diagnostic.expectedHash': 'Oczekiwany prefiks skrótu',
  'referenceFatal.diagnostic.actualHash': 'Rzeczywisty prefiks skrótu',
  'referenceFatal.diagnostic.locale': 'Ustawienia regionalne',
  'referenceFatal.reason.manifestFetch': 'Nie udało się pobrać manifestu danych referencyjnych.',
  'referenceFatal.reason.manifestInvalid': 'Plik opisu danych referencyjnych jest nieprawidłowy.',
  'referenceFatal.reason.manifestVersion': 'Ta wersja manifestu danych referencyjnych nie jest obsługiwana.',
  'referenceFatal.reason.buildMismatch': 'Dane referencyjne należą do innej wersji aplikacji.',
  'referenceFatal.reason.assetFetch': 'Nie udało się pobrać wymaganego pliku referencyjnego.',
  'referenceFatal.reason.assetContentType': 'Wymagany plik referencyjny został udostępniony z nieprawidłowym typem zawartości.',
  'referenceFatal.reason.assetJson': 'Wymagany plik referencyjny zawiera nieprawidłowy JSON.',
  'referenceFatal.reason.assetSchema': 'Wymagany plik referencyjny ma nieprawidłową strukturę.',
  'referenceFatal.reason.assetSize': 'Wymagany plik referencyjny przekracza dopuszczalny rozmiar.',
  'referenceFatal.reason.assetHash': 'Wymagany plik referencyjny nie odpowiada manifestowi.',
  'referenceFatal.reason.internal': 'Nie udało się ukończyć kontroli integralności danych referencyjnych.',
  'locale.selector.label': 'Język i ustawienia regionalne',
  'locale.selector.automatic': 'Automatycznie ({locale})',
  'locale.selector.current': 'Język i ustawienia regionalne: {locale}',
  'common.about': 'O aplikacji',
  'common.help': 'Pomoc',
  'common.close': 'Zamknij',
  'common.cancel': 'Anuluj',
  'common.cancel.lower': 'anuluj',
  'common.save': 'zapisz',
  'common.edit': 'edytuj',
  'common.add': '+ Dodaj',
  'common.removeItem': 'Usuń pozycję: {item}',
  'common.moveUp': 'Przenieś wyżej: {item}',
  'common.moveDown': 'Przenieś niżej: {item}',
  'common.dragToReorder': 'Przeciągnij, aby zmienić kolejność: {item}',
  'common.expandItem': 'Rozwiń: {item}',
  'common.collapseItem': 'Zwiń: {item}',
  'about.closeDialog': 'Zamknij okno „O aplikacji”',
  'about.description': 'Narzędzie do śledzenia sieci placówek w Starfield.',
  'about.attribution': 'designed by gravisio from Flaticon',
  'shortcuts.title': 'Skróty klawiaturowe',
  'shortcuts.closeDialog': 'Zamknij okno skrótów klawiaturowych',
  'shortcuts.introduction': 'Polecenia globalne dostępne w całej aplikacji. Skróty nie przechwytują klawiszy podczas edycji tekstu ani w otwartych oknach dialogowych, gdy wymaga tego kontekst.',
  'shortcuts.group.history': 'Historia',
  'shortcuts.group.search': 'Wyszukiwanie',
  'shortcuts.group.outpostNavigation': 'Nawigacja po placówkach',
  'shortcuts.group.workspace': 'Obszar roboczy',
  'shortcuts.group.resourceMatrix': 'Macierz zasobów',
  'shortcuts.group.cargoLinks': 'Połączenia towarowe',
  'shortcuts.group.importExport': 'Importowanie / eksportowanie',
  'shortcuts.group.validation': 'Walidacja',
  'shortcuts.action.undo': 'Cofnij',
  'shortcuts.action.redo': 'Ponów',
  'shortcuts.action.focusSearch': 'Przejdź do wyszukiwania pozycji',
  'shortcuts.action.focusSearchResults': 'Przejdź do wyników wyszukiwania',
  'shortcuts.action.addOutpost': 'Dodaj placówkę',
  'shortcuts.action.previousOutpost': 'Poprzednia placówka',
  'shortcuts.action.nextOutpost': 'Następna placówka',
  'shortcuts.action.toggleNavigation': 'Pokaż/ukryj nawigację',
  'shortcuts.action.focusNavigation': 'Przejdź do nawigacji',
  'shortcuts.action.focusOutpostDetails': 'Przejdź do szczegółów placówki',
  'shortcuts.action.focusPlannedSupply': 'Przejdź do planowanego zaopatrzenia',
  'shortcuts.action.focusResourceMatrix': 'Przejdź do macierzy zasobów',
  'shortcuts.action.focusFirstInorganic': 'Nieorganiczne',
  'shortcuts.action.focusFirstOrganic': 'Organiczne',
  'shortcuts.action.focusManufacturingAction': 'Wytwarzanie',
  'shortcuts.action.focusCargoLinks': 'Przejdź do połączeń towarowych',
  'shortcuts.action.addCargoLink': 'Dodaj połączenie towarowe',
  'shortcuts.action.expandAllCargoLinks': 'Rozwiń wszystkie',
  'shortcuts.action.collapseAllCargoLinks': 'Zwiń wszystkie',
  'shortcuts.action.import': 'Importuj',
  'shortcuts.action.export': 'Eksportuj',
  'shortcuts.action.toggleValidation': 'Przełącz szczegóły walidacji',
  'character.name': 'Postać',
  'character.level': 'Poziom',
  'character.level.rejectedRestored': 'Nieprawidłowy poziom. Przywrócono wartość {value}. Wprowadź poziom od 1 do 999.',
  'character.level.rejectedEmpty': 'Nieprawidłowy poziom. Przywrócono poprzednią wartość. Wprowadź poziom od 1 do 999.',
  'character.skillRank.rejectedRestored': 'Nieprawidłowa ranga. Przywrócono wartość {value}. Wprowadź rangę od 0 do 4.',
  'character.skillRank.rejectedEmpty': 'Nieprawidłowa ranga. Przywrócono poprzednią wartość. Wprowadź rangę od 0 do 4.',
  'character.skill.outpostManagement': 'Zarządzanie placówką',
  'character.skill.outpostEngineering': 'Inżynieria placówek',
  'character.skill.planetaryHabitation': 'Zasiedlanie planet',
  'character.skill.researchMethods': 'Metody badawcze',
  'character.skill.specialProjects': 'Projekty specjalne',
  'network.label': 'SIEĆ',
  'network.active': 'Aktywna sieć',
  'network.previous': 'Poprzednia sieć',
  'network.next': 'Następna sieć',
  'network.add': 'Dodaj sieć',
  'network.reset.button': 'Zresetuj sieć',
  'network.reset.confirmTitle': 'ZRESETUJ SIEĆ',
  'network.reset.explanation': 'Zresetować bieżącą sieć do nowego stanu domyślnego?',
  'network.delete.button': 'Usuń sieć',
  'network.delete.confirmTitle': 'USUŃ SIEĆ',
  'network.delete.explanation': 'Usunąć bieżącą sieć z tej kolekcji?',
  'network.delete.undoHint': 'Możesz cofnąć tę czynność podczas bieżącej sesji.',
  'outpost.defaultName': 'Nowa placówka',
  'outpost.delete': 'Usuń placówkę',
  'outpost.navigation.heading': 'Placówki',
  'outpost.navigation.hide': 'Ukryj nawigację po placówkach',
  'outpost.navigation.show': 'Pokaż nawigację po placówkach',
  'outpost.navigation.add': 'Dodaj placówkę',
  'outpost.navigation.addButton': '+ Dodaj placówkę',
  'outpost.navigation.lockOrder': 'Zakończ zmianę kolejności',
  'outpost.navigation.reshuffleButton': 'Zmień kolejność',
  'outpost.navigation.addWithLimit': 'Dodaj placówkę ({count} z {limit})',
  'outpost.navigation.reshuffle': 'Zmień kolejność placówek',
  'outpost.navigation.finishReshuffle': 'Zakończ zmianę kolejności placówek',
  'outpost.name.label': 'Nazwa placówki',
  'outpost.details.heading': 'Szczegóły placówki',
  'outpost.system.label': 'Układ',
  'outpost.system.select': 'Wybierz układ...',
  'outpost.body.label': 'Ciało planetarne',
  'outpost.body.select': 'Wybierz ciało planetarne...',
  'outpost.solar.label': 'Energia słoneczna',
  'outpost.wind.label': 'Energia wiatrowa',
  'outpost.biomes.label': 'Biomy',
  'outpost.referenceData.empty': 'Nie znaleziono danych referencyjnych zasobów dla tego ciała planetarnego.',
  'power.label.veryPoor': 'B. słaba',
  'power.label.poor': 'Słaba',
  'power.label.normal': 'Średnia',
  'power.label.good': 'Dobra',
  'power.label.none': 'Brak',
  'power.label.unknown': '—',
  'power.quality.veryPoor': 'Bardzo słaba',
  'power.quality.poor': 'Słaba',
  'power.quality.normal': 'Normalna',
  'power.quality.good': 'Dobra',
  'power.quality.none': 'Brak',
  'power.quality.unknown': 'Nieznana',
  'power.tooltip.unknown': '{source}: {quality}',
  'power.tooltip.noModifier': '{source}: {quality} · moc wyjściowa {multiplier}× (bez modyfikatora)',
  'power.tooltip.modified': '{source}: {quality} · moc wyjściowa {multiplier}× ({modifier})',
  'matrix.heading': 'Macierz zasobów',
  'production.heading': 'Aktywna produkcja',
  'production.empty': 'Nie wybrano żadnych zasobów lokalnych.',
  'matrix.column.item': 'Pozycja',
  'matrix.column.source': 'Źródło',
  'matrix.column.present': 'Obecność',
  'matrix.column.producing': 'W produkcji',
  'matrix.column.inputs': 'Wymagane materiały',
  'matrix.column.logistics': 'Logistyka',
  'matrix.section.inorganic': 'Nieorganiczne',
  'matrix.section.organic': 'Organiczne',
  'matrix.section.manufacturing': 'Wytwarzanie',
  'matrix.section.imports': 'Import',
  'matrix.manufacturing.add': 'Dodaj wytwarzany produkt',
  'matrix.manufacturing.addLabel': 'Dodaj produkt',
  'matrix.manufacturing.select': 'Wybierz produkt...',
  'matrix.manufacturing.empty': 'Nie skonfigurowano wytwarzania.',
  'matrix.imports.empty': 'Brak importu.',
  'matrix.state.active': '{item}: stan aktywny',
  'matrix.state.inactive': '{item}: stan nieaktywny',
  'matrix.action.toggle': '{action}: {item}',
  'matrix.action.togglePresent': 'Przełącz obecność: {item}',
  'matrix.action.toggleProducing': 'Przełącz produkcję: {item}',
  'matrix.action.toggleProducingSource': 'Przełącz produkcję — źródło: {source}; pozycja: {item}',
  'matrix.source.unspecified': 'Nieokreślone',
  'plannedSupply.heading': 'Planowane zaopatrzenie',
  'plannedSupply.empty': 'Brak planowanego zaopatrzenia.',
  'plannedSupply.section.inorganic': 'Zasoby nieorganiczne',
  'plannedSupply.section.organic': 'Zasoby organiczne',
  'plannedSupply.section.products': 'Wytwarzane produkty',
  'plannedSupply.remove': 'Usuń z planowanego zaopatrzenia: {item}',
  'plannedSupply.add': 'Dodaj do planowanego zaopatrzenia: {item}',
  'plannedSupply.removeAll': 'Usuń całe planowane zaopatrzenie',
  'plannedSupply.addItems': 'Dodaj pozycje do planowanego zaopatrzenia',
  'plannedSupply.expand': 'Rozwiń planowane zaopatrzenie',
  'plannedSupply.collapse': 'Zwiń planowane zaopatrzenie',
  'cargo.heading': 'Połączenia towarowe',
  'cargo.add': 'Dodaj połączenie towarowe',
  'cargo.addButton': '+ Dodaj połączenie towarowe',
  'cargo.expandAll': 'Rozwiń wszystkie',
  'cargo.collapseAll': 'Zwiń wszystkie',
  'cargo.lockOrder': 'Zakończ zmianę kolejności',
  'cargo.reshuffleButton': 'Zmień kolejność',
  'cargo.addWithLimit': 'Dodaj połączenie towarowe ({count} z {limit})',
  'cargo.reshuffle': 'Zmień kolejność połączeń towarowych',
  'cargo.finishReshuffle': 'Zakończ zmianę kolejności połączeń towarowych',
  'cargo.exports.heading': 'Eksport',
  'cargo.export.toggle': 'Przełącz eksport: {item}',
  'cargo.destination.outpost': 'Placówka docelowa',
  'cargo.destination.pad': 'Docelowe połączenie towarowe',
  'cargo.destination.unlinked': 'Niepołączone',
  'cargo.interstellar': 'Międzyukładowe połączenie towarowe',
  'cargo.interSystem.button': 'Międzyukładowe',
  'cargo.interSystem.context': 'Międzyukładowe połączenia towarowe',
  'cargo.remove': 'Usuń',
  'cargo.destination.noPads': '{outpost} — brak połączeń towarowych',
  'cargo.destination.selectPad': 'Wybierz połączenie towarowe...',
  'cargo.destination.nothing': 'brak',
  'cargo.destination.unknownPad': 'Nieznane połączenie towarowe',
  'cargo.destination.unknownPadInline': 'nieznane połączenie towarowe',
  'cargo.destination.padContents': '{pad}: ({contents})',
  'cargo.destination.padContentsLinked': '{pad}: ({contents}) — cel: {destination}',
  'cargo.destination.linkedLocator': '{outpost} / {pad}',
  'cargo.exports.empty': 'Brak pozycji dostępnych do eksportu.',
  'cargo.pad.remove': 'Usuń: {pad}',
  'cargo.pad.summary': 'Połączenie towarowe {ordinal}',
  'cargo.pad.count': '{count, plural, one {} other {}}Liczba połączeń towarowych: {count}',
  'cargo.pad.emptyExports': 'Brak eksportu',
  'cargo.pad.noDestination': 'Niepołączone',
  'cargo.pad.linkedTo': 'Połączono z: {outpost}',
  'cargo.pad.semanticSummary': 'Miejsce docelowe: {destination}. Wysyłane: {outbound}. Odbierane: {inbound}. {linkType}.',
  'cargo.pad.noOutboundCargo': 'Brak wysyłanego ładunku',
  'cargo.pad.noInboundCargo': 'Brak odbieranego ładunku',
  'cargo.pad.linkType.standard': 'Standardowe połączenie towarowe',
  'cargo.pad.linkType.interSystem': 'Międzyukładowe połączenie towarowe',
  'validation.heading': 'Walidacja',
  'validation.none': 'Brak problemów wykrytych przez walidację.',
  'validation.counts': 'Błędy: {errors} · Ostrzeżenia: {warnings} · Informacje: {info}',
  'validation.filter.all': 'Wszystkie',
  'validation.filter.error': 'Błędy',
  'validation.filter.warning': 'Ostrzeżenia',
  'validation.filter.info': 'Informacje',
  'validation.severity.error': 'Błąd',
  'validation.severity.warning': 'Ostrzeżenie',
  'validation.severity.info': 'Informacja',
  'validation.open': 'Otwórz szczegóły walidacji',
  'validation.close': 'Zamknij szczegóły walidacji',
  'validation.context.pad': 'Połączenie towarowe {ordinal}',
  'validation.context.separator': '{outpost} · {pad}',
  'validation.issueCount': '{count, plural, one {} other {}}Walidacja — liczba problemów: {count}',
  'validation.manufacturingInputUnavailable': 'Produkt: {product}. Wymagany materiał jest niedostępny w tej placówce: {input}.',
  'validation.plannedSupplyUnresolved': '{count, plural, one {} other {}}Planowane zaopatrzenie — liczba nierozwiązanych pozycji: {count}. Pozycje: {itemList}.',
  "validation.activeProductionOrganicInvalid": "Oznaczono jako produkowany zasób: {resource}. Ten producent nie kwalifikuje się do produkcji organicznej na tej planecie.",
  'validation.activeProductionInorganicInvalid': 'Oznaczono jako produkowany zasób: {resource}. Nie jest on dostępny do wydobycia w placówce w następujących biomach: {biomes}.',
  "validation.activeProductionOrganicInvalidOne": "Oznaczono jako produkowany zasób: {resource}. Ten producent nie kwalifikuje się do produkcji organicznej na tej planecie.",
  "validation.activeProductionOrganicInvalidMany": "Oznaczono jako produkowany zasób: {resource}. Ten producent nie kwalifikuje się do produkcji organicznej na tej planecie.",
  'validation.activeProductionInorganicInvalidOne': 'Oznaczono jako produkowany zasób: {resource}. Nie jest on dostępny do wydobycia w placówce w biomie: {biomes}.',
  'validation.activeProductionInorganicInvalidMany': 'Oznaczono jako produkowany zasób: {resource}. Nie jest on dostępny do wydobycia w placówce w biomach: {biomes}.',
  'validation.bodySystemMismatch': 'Ciało planetarne wybrane dla tej placówki nie należy do wybranego układu gwiezdnego.',
  'validation.cargoPadLinkedMultiple': 'To połączenie towarowe ma więcej niż jedno połączenie.',
  'validation.cargoPadSkillLimit': 'Liczba połączeń towarowych w tej placówce: {count}. Umiejętność „{skill}” na obecnym poziomie pozwala na maksymalnie {limit}.',
  'validation.duplicateLocalResource': 'Pozycja występuje więcej niż raz w zasobach lokalnych tej placówki: {item}.',
  'validation.duplicateActiveProduction': 'Pozycja występuje więcej niż raz w aktywnej produkcji tej placówki: {item}.',
  'validation.duplicateExplicitPresence': 'Pozycja występuje więcej niż raz w jawnej obecności zasobów tej placówki: {item}.',
  'validation.duplicateBiome': 'Pozycja występuje więcej niż raz w wyborze biomów tej placówki: {item}.',
  'validation.duplicateManufacturing': 'Pozycja występuje więcej niż raz na liście wytwarzania tej placówki: {item}.',
  'validation.duplicatePlannedSupply': 'Pozycja występuje więcej niż raz w planowanym zaopatrzeniu tej placówki: {item}.',
  'validation.duplicateOutboundItem': 'Pozycja występuje więcej niż raz w ładunku wychodzącym tego połączenia towarowego: {item}.',
  'validation.duplicateOutpostName': 'Liczba placówek o nazwie „{name}”: {count}. Zaleca się używanie unikatowych nazw placówek, aby uniknąć niejednoznaczności.',
  'validation.interstellarHelium3': 'To międzyukładowe połączenie towarowe wysyła ładunek, ale w jego placówce nie ma dostępnego zaopatrzenia w hel-3.',
  'validation.invalidCharacterLevel': 'Poziom postaci: {level}. Zapisany poziom musi być liczbą całkowitą od {minimum} do {maximum}.',
  'validation.invalidSkillLevel': 'Umiejętność: {skill}. Poziom: {level}. Prawidłowe poziomy to liczby całkowite od {minimum} do {maximum}.',
  'validation.missingCargoEndpoint': 'Połączenie ładunkowe odwołuje się do brakującej placówki lub brakującego punktu końcowego połączenia towarowego.',
  'validation.organicInputUnavailable': 'Gatunek: {species}. Wymagany materiał jest niedostępny w tej placówce: {input}.',
  'validation.outpostBodyNotEligible': 'Ta placówka znajduje się na ciele planetarnym, na którym nie można budować placówek.',
  'validation.characterNameLength': 'Imiona postaci w Starfield mają zwykle maksymalnie 25 znaków.',
  'validation.outpostNameLength': 'Starfield zwykle ogranicza nazwy placówek do 25 znaków; dłuższe nazwy dodane przez mody pozostają obsługiwane.',
  'validation.outpostSkillLimit': 'Liczba placówek w tej sieci: {count}. Umiejętność „{skill}” na obecnym poziomie pozwala na maksymalnie {limit}.',
  'validation.planetaryHabitationRequirement': 'Ta placówka wymaga rangi {required}. Umiejętność: {skill}. Zapisana ranga postaci: {recorded}.',
  'validation.regularPadCrossSystem': 'Połączenie towarowe prowadzi do placówki w innym układzie gwiezdnym; zamiast niego użyj międzyukładowego połączenia towarowego.',
  'validation.selectedBiomeInvalid': 'Wybrany biom należy do innego ciała planetarnego.',
  'validation.selfLinkedCargoPad': 'To połączenie ładunkowe używa tego samego połączenia towarowego na obu końcach.',
  'validation.unknownSystem': 'Ta placówka odwołuje się do nieznanego ID układu gwiezdnego: „{id}”.',
  'validation.unknownBody': 'Ta placówka odwołuje się do nieznanego ID ciała planetarnego: „{id}”.',
  'validation.unknownLocalResource': 'Ta placówka odwołuje się w zasobach lokalnych do nieznanego ID zasobu: „{id}”.',
  'validation.unknownBiome': 'Ta placówka odwołuje się do nieznanego ID biomu ciała planetarnego: „{id}”.',
  'validation.unknownExplicitResource': 'Ta placówka odwołuje się w jawnej obecności zasobów do nieznanego ID zasobu: „{id}”.',
  'validation.unknownProductionResource': 'Ta placówka odwołuje się w aktywnej produkcji do nieznanego ID zasobu: „{id}”.',
  'validation.unknownProductionSpecies': 'Ta placówka odwołuje się w aktywnej produkcji do nieznanego ID gatunku: „{id}”.',
  'validation.unknownManufacturingProduct': 'Ta placówka odwołuje się na liście wytwarzania do nieznanego ID produktu: „{id}”.',
  'validation.unknownPlannedItem': 'Ta placówka odwołuje się w planowanym zaopatrzeniu do nieznanego ID. Rodzaj: {kind}; ID: „{id}”.',
  'validation.unknownOutboundItem': 'Połączenie towarowe odwołuje się w ładunku wychodzącym do nieznanego ID. Rodzaj: {kind}; ID: „{id}”.',
  'validation.unspecifiedOrganicSource': 'Oznaczono jako produkowany zasób: {resource}. Nie określono jednak źródła flory ani fauny.',
  'validation.unresolvedCargoExport': 'Ten eksport ładunku nie ma rzeczywistego źródła.',
  'validation.xTechCapabilityProduced': 'Oznaczono jako produkowany zasób: {resource}. Postać nie ma wymaganej zdolności wydobywczej.',
  'validation.xTechCapabilityPresent': 'Oznaczono obecność zasobu: {resource}. Postać nie ma wymaganej zdolności wydobywczej.',
  'validation.xTechRequiresPresence': 'Oznaczono jako produkowany zasób: {resource}. Jego obecność w tej placówce nie została jawnie zapisana.',
  'validation.remediation.extraction': 'Dostępność do wydobycia — biomy: {biomes}',
  "validation.remediation.harvesting": "Wybierz prawidłowego producenta możliwego do hodowli na tej planecie.",
  'validation.remediation.organicSources': 'Dostępne źródła: {sources}',
  'status.dismiss': 'Odrzuć komunikat o stanie',
  'status.storage.recovery': 'Nie udało się przywrócić danych zapisanych w przeglądarce. Używana jest kolekcja tymczasowa; oryginał zostanie zachowany do czasu edycji.',
  'status.storage.unavailable': 'Pamięć przeglądarki jest niedostępna. Ta kolekcja znajduje się wyłącznie w pamięci operacyjnej.',
  'status.storage.unsaved': 'Zmiany znajdują się wyłącznie w pamięci operacyjnej i nie zostały zapisane w tej przeglądarce.',
  'status.storage.capacity': 'Ta kolekcja jest zbyt duża, aby można ją było bezpiecznie zapisać. Zmiany pozostają w pamięci operacyjnej.',
  'status.dismiss.short': 'Odrzuć',
  'status.export.success': 'Wyeksportowano plik: {fileName}.',
  'status.import.success': 'Zaimportowano plik: {fileName}.',
  'status.import.failed': 'Nie udało się wczytać pliku {fileName}: {reason}',
  'status.import.readFailed': 'Nie udało się odczytać wybranego pliku.',
  'status.import.invalid': 'Nie udało się zaimportować wybranego pliku.',
  'status.import.invalidJson': 'Wybrany plik nie zawiera prawidłowego JSON.',
  'status.import.invalidCollection': 'Wybrany plik nie jest prawidłową kolekcją sieci.',
  'status.import.emptyCollection': 'Wybrana kolekcja nie zawiera żadnych sieci.',
  'status.import.malformedEntry': 'Wybrana kolekcja zawiera nieprawidłowy wpis sieci.',
  'status.import.duplicateNetworkId': 'Wybrana kolekcja zawiera zduplikowany ID sieci: „{id}”.',
  'status.import.unsupportedCollectionSchema': 'Nieobsługiwana wersja schematu kolekcji sieci: {version}',
  'status.import.invalidCharacter': 'Wybrany plik zawiera nieprawidłowe dane postaci.',
  'status.import.invalidCapabilities': 'Wybrany plik zawiera nieprawidłowe dane zdolności postaci.',
  'status.import.invalidSkills': 'Wybrany plik zawiera nieprawidłowe dane umiejętności postaci.',
  'status.import.invalidNetwork': 'Wybrany plik nie jest prawidłową siecią placówek.',
  'status.import.unsupportedNetworkSchema': 'Nieobsługiwana wersja schematu sieci: {version}',
  'status.import.invalidOutpost': 'Wybrany plik zawiera nieprawidłową placówkę.',
  'status.import.invalidExplicitPresence': 'Wybrany plik zawiera nieprawidłowe dane jawnej obecności zasobów.',
  'status.import.invalidCargoPad': 'Wybrany plik zawiera nieprawidłowe połączenie towarowe.',
  'status.import.invalidStructure': 'Wybrany plik zawiera nieprawidłową strukturę danych sieci.',
  'status.import.invalidIdentity': 'Wybrany plik zawiera pusty lub zduplikowany stabilny identyfikator.',
  'status.import.fileTooLarge': 'Wczytywane dane są zbyt duże, aby można je było bezpiecznie otworzyć.',
  'status.import.arrayLimitExceeded': 'Wczytywane dane zawierają zbyt wiele pozycji w jednej sekcji.',
  'status.import.tooManyNetworks': 'Wczytywane dane zawierają zbyt wiele zapisanych sieci.',
  'status.import.aggregateLimitExceeded': 'Wczytywane dane zawierają zbyt wiele pozycji, aby można je było bezpiecznie otworzyć.',
  'status.import.stringTooLong': 'Wczytywane dane zawierają zbyt długą wartość tekstową.',
  'status.referenceData.failed': 'Nie udało się wczytać danych referencyjnych.',
  'status.referenceData.error': 'Błąd danych referencyjnych: {detail}',
  'status.referenceData.loaded': 'Wczytano dane referencyjne. Układy: {systems}; ciała planetarne: {bodies}; zasoby: {resources}; produkty: {products}.',
  'status.referenceData.reload': 'Wczytaj ponownie dane referencyjne',
  'status.drag.reorder': 'Upuść, aby zmienić kolejność · Esc — anuluj',
  'transfer.export.button': 'Eksportuj',
  'transfer.export.tooltip': 'Eksportuj wszystkie sieci do JSON',
  'transfer.import.button': 'Importuj',
  'transfer.import.tooltip': 'Importuj wszystkie sieci z JSON',
  'history.undo': 'Cofnij',
  'history.redo': 'Ponów',
  'history.undo.action': 'Cofnij: {action}',
  'history.redo.action': 'Ponów: {action}',
  'history.undo.none': 'Brak czynności do cofnięcia',
  'history.redo.none': 'Brak czynności do ponowienia',
  'history.networkContext': 'Sieć {ordinal}: {action}',
  'history.addNetwork': 'Dodaj sieć',
  'history.deleteNetwork': 'Usuń sieć',
  'history.resetNetwork': 'Zresetuj sieć',
  'history.importNetworks': 'Importuj sieci',
  'history.benchmark': '{label}',
  'history.renameCharacter': 'Zmień nazwę postaci: {previousName} → {name}',
  'history.clearCharacterLevel': 'Wyczyść poziom postaci',
  'history.setCharacterLevel': 'Ustaw poziom postaci: {level}',
  'history.changeCharacterLevel': 'Zmień poziom postaci: {previousLevel} → {level}',
  'history.clearSkill': 'Wyczyść rangę umiejętności: {skill}',
  'history.setSkill': 'Ustaw rangę umiejętności: {skill} — {rank}',
  'history.changeSkill': 'Zmień rangę umiejętności: {skill} — {previousRank} → {rank}',
  'history.moveOutpost': 'Przenieś placówkę na pozycję {position}: {outpost}',
  'history.addOutpost': 'Dodaj placówkę',
  'history.deleteOutpost': 'Usuń placówkę: {outpost}',
  'history.moveCargoPad': 'Przenieś na pozycję {position}: {outpost} / {pad}',
  'history.addCargoPad': 'Dodaj: {outpost} / {pad}',
  'history.deleteCargoPad': 'Usuń: {outpost} / {pad}',
  'history.unlinkCargoPad': 'Rozłącz: {outpost} / {pad}',
  'history.linkCargoPad': 'Połącz: {localOutpost} / {localPad} → {remoteOutpost} / {remotePad}',
  'history.changeCargoLink': 'Zmień połączenie: {localOutpost} / {localPad} → {remoteOutpost} / {remotePad}',
  'history.addExport': 'Dodaj eksport — pozycja: {item}; połączenie: {outpost} / {pad}',
  'history.removeExport': 'Usuń eksport — pozycja: {item}; połączenie: {outpost} / {pad}',
  'history.changeCargoPadType': 'Zmień typ: {outpost} / {pad} → {type}',
  'history.renameOutpost': 'Zmień nazwę placówki: {previousName} → {name}',
  'history.changeSystem': 'Zmień układ — placówka: {outpost}; układ: {system}',
  'history.clearSystem': 'Wyczyść układ — placówka: {outpost}',
  'history.changeBody': 'Zmień ciało planetarne — placówka: {outpost}; ciało: {body}',
  'history.clearBody': 'Wyczyść ciało planetarne — placówka: {outpost}',
  'history.addBiome': 'Dodaj wybór biomu — placówka: {outpost}',
  'history.removeBiome': 'Usuń wybór biomu — placówka: {outpost}',
  'history.addLocalResource': 'Dodaj zasób lokalny — zasób: {resource}; placówka: {outpost}',
  'history.removeLocalResource': 'Usuń zasób lokalny — zasób: {resource}; placówka: {outpost}',
  'history.addExplicitResource': 'Dodaj jawną obecność zasobu — zasób: {resource}; placówka: {outpost}',
  'history.removeExplicitResource': 'Usuń jawną obecność zasobu — zasób: {resource}; placówka: {outpost}',
  'history.startProducing': 'Rozpocznij produkcję — zasób: {resource}; placówka: {outpost}',
  'history.stopProducing': 'Zatrzymaj produkcję — zasób: {resource}; placówka: {outpost}',
  'history.editManufacturing': 'Edytuj wytwarzanie — placówka: {outpost}',
  'history.addPlannedSupply': 'Dodaj do planowanego zaopatrzenia: {item}',
  'history.removePlannedSupply': 'Usuń z planowanego zaopatrzenia: {item}',
  'help.plannedSupply': 'Wybrane pozycje służą jako symbole zastępcze do czasu zapewnienia lokalnego lub importowanego zaopatrzenia.',
  'help.logistics': 'Tutaj są wyświetlane pozycje przypisane obecnie do połączeń towarowych.',
  "help.biomes": "Wybrane biomy ograniczają dostępność zasobów nieorganicznych do tych, które mogą w nich występować.",
  'help.present': 'Wskazuje, czy zasób może występować w tej placówce.',
  'help.producing': 'Wskazuje, czy ta placówka jest skonfigurowana do produkcji danego zasobu lub produktu.',
  'help.interSystem': 'Międzyukładowe połączenia towarowe mogą łączyć placówki w różnych układach gwiezdnych i wymagają helu-3.',
  'help.validation': 'Błędy oznaczają nieprawidłowe stany, ostrzeżenia — stany niepełne lub niespójne, a informacje wskazują przydatne dalsze działania.',
  'help.forContext': 'Pomoc — kontekst: {context}',
  "help.organic.unavailablePlanet": "Ten gatunek możliwy do hodowli na tej planecie nie zapewnia zasobu: {resource}.",
  "help.organic.unavailableBiome": "Ten gatunek możliwy do hodowli na tej planecie nie zapewnia zasobu: {resource}.",
  "help.organic.unavailableBiomes": "Ten gatunek możliwy do hodowli na tej planecie nie zapewnia zasobu: {resource}.",
  "help.organic.availablePlanet": "Zasób jest dostępny z gatunku możliwego do hodowli na tej planecie: {resource}.",
  "help.organic.availableBiome": "Zasób jest dostępny z gatunku możliwego do hodowli na tej planecie: {resource}.",
  "help.organic.availableSelectedBiome": "Zasób jest dostępny z gatunku możliwego do hodowli na tej planecie: {resource}.",
  "help.organic.availableBiomes": "Zasób jest dostępny z gatunku możliwego do hodowli na tej planecie: {resource}.",
  'help.inorganicPresentRecorded': 'Jawnie zapisano obecność zasobu w tej placówce: {resource}.',
  'help.contextLabel': 'Pomoc — kontekst: {context}',
  'help.inorganicPresentPossible': 'Ten zasób może występować w placówce: {resource}.',
  'matrix.action.xTech.add': 'Dodaj jako obecny zasób: {resource}',
  'matrix.tooltip.xTech.add': 'Dodaj jako obecny zasób: {resource}. Można go wydobywać w dowolnej placówce, jeśli dostępne są rdzenie mocy X-Techu.',
  'matrix.tooltip.xTech.present': 'Jawnie zapisano obecność tego zasobu w placówce: {resource}.',
  'matrix.tooltip.producing.active': 'Pozycja jest produkowana w tej placówce: {item}.',
  'matrix.tooltip.producing.inactive': 'Pozycja nie jest produkowana w tej placówce: {item}.',
  'matrix.tooltip.manufacturing.blocked': 'Pozycja nie jest produkowana w tej placówce z powodu braku wymaganych materiałów: {item}.',
  'matrix.tooltip.input.available': 'Pozycja jest dostępna w tej placówce: {item}.',
  'matrix.tooltip.input.unavailable': 'Pozycja jest niedostępna w tej placówce: {item}.',
  'matrix.tooltip.export.active': 'Pozycja: {item}. Eksport do: {destinations}.',
  'matrix.tooltip.export.inactive': 'Pozycja nie jest eksportowana: {item}.',
  'matrix.tooltip.import.active': 'Pozycja jest importowana: {item}.',
  'search.input.label': 'Wyszukaj zasoby lub produkty w swoich placówkach.',
  'search.input.placeholder': 'Wyszukaj zasoby lub produkty',
  'search.input.description': 'Wpisz nazwę lub skrót pozycji, a następnie potwierdź pozycję do wyszukania.',
  'search.submit': 'Wyszukaj pozycję',
  'search.autocomplete.resource': 'Zasób',
  'search.autocomplete.product': 'Produkt',
  'search.results.title': 'Wyniki wyszukiwania',
  'search.results.found': '{count, plural, one {} other {}}Liczba placówek, w których znaleziono pozycję „{searchItem}”: {count}.',
  'search.results.notFound': 'Nie znaleziono pozycji „{searchItem}” w żadnej placówce.',
  'search.results.close': 'Zamknij wyniki wyszukiwania',
  'search.results.flag.present': 'Obecność',
  'search.results.flag.producing': 'W produkcji',
  'search.results.flag.missingInputs': 'Brakujące materiały',
  'search.results.flag.importing': 'Importowanie',
  'search.results.flag.exporting': 'Eksportowanie',
  'search.results.flag.plannedSupply': 'Planowane zaopatrzenie',
  'search.results.dragInstructions': 'Przesuwaj wyniki wyszukiwania klawiszami strzałek. Przytrzymaj Shift, aby wykonywać większe kroki.',
} satisfies MessageCatalogue
