import { buildReviewDraft } from './buildDraft.ts'

/** Independent Brazilian Portuguese Codex draft used only by the semantic review package. */
export const ptBRReviewDraft = buildReviewDraft({
  "about.version": "Versão {version}",
  "about.build": "Compilação {commit}",
  "about.modified": "local / modificada",
  "about.unknown": "local / não verificada",
  "about.licenseSummary": "Código criado para o projeto: GPL-3.0-or-later, sem garantia. A arte e o conteúdo derivado do jogo estão sujeitos a direitos separados.",
  "about.license": "Licença completa",
  "about.notices": "Avisos de terceiros",
  "about.repository": "Repositório do código-fonte",
  "about.buildSource": "Código-fonte desta compilação",
  "about.issues": "Erros e sugestões",
  "about.contact": "Contato privado / alternativo",
  "about.support": "Apoie Gooberpede",
  "about.funding": "Apoio voluntário ao trabalho do desenvolvedor em mods e ferramentas para jogos Bethesda. Os projetos publicados são gratuitos; gorjetas ou assinaturas não compram recursos extras, exclusividades, acesso, suporte prioritário nem compromissos de entrega.",
  "about.backup": "Os dados são salvos neste perfil do navegador neste site, sem sincronização de conta nem backup no servidor. Exporte antes de apagar os dados do navegador ou trocar de dispositivo. A importação substitui a coleção. Se o salvamento falhar, exporte o trabalho que está na memória.",
  "about.unofficial": "Projeto independente e não oficial, sem afiliação ou endosso da Bethesda Game Studios ou da Microsoft.",
  "about.artwork": "Arte do ícone do site (licença separada):",
  'about.attribution': 'designed by gravisio from Flaticon',
  'referenceFatal.explanation': 'Não foi possível carregar corretamente os dados de referência obrigatórios. O aplicativo foi interrompido para proteger o trabalho salvo.',
  'referenceFatal.privacy': 'O envio do relatório abre o aplicativo de e-mail e inclui somente diagnósticos técnicos. Nenhum dado salvo da rede é incluído automaticamente.',
  'shortcuts.introduction': 'Comandos globais disponíveis em todo o aplicativo. Os atalhos cedem prioridade à edição de texto e às caixas de diálogo abertas quando necessário.',
  'character.level.rejectedRestored': 'Nível inválido. {value} foi restaurado. Digite um nível de 1 a 999.',
  'character.level.rejectedEmpty': 'Nível inválido. O valor anterior foi restaurado. Digite um nível de 1 a 999.',
  'character.skillRank.rejectedRestored': 'Grau inválido. {value} foi restaurado. Digite um grau de 0 a 4.',
  'character.skillRank.rejectedEmpty': 'Grau inválido. O valor anterior foi restaurado. Digite um grau de 0 a 4.',
  'network.reset.explanation': 'Redefinir a rede atual para um novo estado padrão?',
  'network.delete.explanation': 'Remover a rede atual desta coleção?',
  'network.delete.undoHint': 'Você pode desfazer esta ação durante a sessão atual.',
  'matrix.column.present': 'Presença',
  'matrix.column.producing': 'Em produção',
  'matrix.column.inputs': 'Insumos',
  'matrix.column.logistics': 'Logística',
  'plannedSupply.heading': 'Suprimento planejado',
  'cargo.pad.semanticSummary': 'Destino: {destination}. Saída: {outbound}. Entrada: {inbound}. {linkType}.',
  'cargo.pad.count': '{count} {count, plural, one {vínculo de carga} other {vínculos de carga}}',
  'validation.issueCount': 'Validação: {count} {count, plural, one {problema} other {problemas}}',
  'validation.manufacturingInputUnavailable': '{product} requer {input}, mas {input} não está disponível neste entreposto.',
  'validation.plannedSupplyUnresolved': '{count} {count, plural, one {item} other {itens}} em Suprimento planejado: {itemList}.',
  "validation.activeProductionOrganicInvalid": "{resource} consta como produzido, mas este produtor não é elegível para produção orgânica neste planeta.",
  'validation.activeProductionInorganicInvalid': '{resource} consta como produzido, mas não está disponível para extração no entreposto em {biomes}.',
  "validation.activeProductionOrganicInvalidOne": "{resource} consta como produzido, mas este produtor não é elegível para produção orgânica neste planeta.",
  "validation.activeProductionOrganicInvalidMany": "{resource} consta como produzido, mas este produtor não é elegível para produção orgânica neste planeta.",
  'validation.activeProductionInorganicInvalidOne': '{resource} consta como produzido, mas não está disponível para extração no entreposto no bioma {biomes}.',
  'validation.activeProductionInorganicInvalidMany': '{resource} consta como produzido, mas não está disponível para extração no entreposto nos biomas {biomes}.',
  'validation.bodySystemMismatch': 'O corpo celeste selecionado para este entreposto não pertence ao sistema estelar selecionado.',
  'validation.cargoPadLinkedMultiple': 'Este vínculo de carga tem mais de uma conexão.',
  'validation.cargoPadSkillLimit': 'Este entreposto tem {count} vínculos de carga, mas o nível atual de {skill} permite no máximo {limit}.',
  'validation.duplicateOutpostName': '{count} entrepostos têm o nome “{name}”. Recomendamos nomes exclusivos para evitar ambiguidades.',
  'validation.interstellarHelium3': 'Este vínculo de carga entre sistemas está enviando carga, mas seu entreposto não dispõe de suprimento de Hélio-3.',
  'validation.invalidCharacterLevel': 'O nível do personagem é {level}, mas um nível registrado precisa ser um número inteiro de {minimum} a {maximum}.',
  'validation.invalidSkillLevel': '{skill} está no nível {level}, mas os níveis válidos são números inteiros de {minimum} a {maximum}.',
  'validation.missingCargoEndpoint': 'Esta conexão de carga faz referência a um entreposto ou uma extremidade de vínculo de carga ausente.',
  'validation.organicInputUnavailable': '{species} requer {input}, mas {input} não está disponível neste entreposto.',
  'validation.outpostBodyNotEligible': 'Este entreposto fica em um corpo celeste que não pode abrigar entrepostos.',
  'validation.characterNameLength': 'Os nomes de personagem em Starfield normalmente têm até 25 caracteres.',
  'validation.outpostNameLength': 'Starfield normalmente limita os nomes dos entrepostos a 25 caracteres; nomes maiores adicionados por mods continuam compatíveis.',
  'validation.outpostSkillLimit': 'Esta rede tem {count} entrepostos, mas o nível atual de {skill} permite no máximo {limit}.',
  'validation.planetaryHabitationRequirement': 'Este entreposto requer grau {required} em {skill}, mas o grau registrado do personagem é {recorded}.',
  'validation.regularPadCrossSystem': 'Este vínculo de carga está conectado a um entreposto em outro sistema estelar; use um vínculo de carga entre sistemas.',
  'validation.selectedBiomeInvalid': 'O bioma selecionado pertence a outro corpo celeste.',
  'validation.selfLinkedCargoPad': 'Esta conexão de carga usa o mesmo vínculo de carga nas duas extremidades.',
  'validation.unspecifiedOrganicSource': '{resource} consta como produzido, mas nenhuma origem de flora ou fauna foi especificada.',
  'validation.unresolvedCargoExport': 'Esta exportação de carga não tem uma origem real.',
  'validation.xTechCapabilityProduced': '{resource} consta como produzido, mas o personagem não tem a capacidade de extração necessária.',
  'validation.xTechCapabilityPresent': '{resource} consta como presente, mas o personagem não tem a capacidade de extração necessária.',
  'validation.xTechRequiresPresence': '{resource} consta como produzido, mas não está registrado explicitamente como presente neste entreposto.',
  'validation.remediation.extraction': 'Disponível para extração em: {biomes}',
  "validation.remediation.harvesting": "Escolha um produtor domesticável válido neste planeta.",
  'validation.remediation.organicSources': 'Disponível em: {sources}',
  'status.storage.recovery': 'Não foi possível restaurar os dados salvos no navegador. Uma coleção temporária está em uso; o original será preservado até uma edição.',
  'status.storage.unavailable': 'O armazenamento do navegador não está disponível. Esta coleção está somente na memória.',
  'status.storage.unsaved': 'As alterações estão somente na memória e não foram salvas neste navegador.',
  'status.storage.capacity': 'Esta coleção é grande demais para ser salva com segurança. As alterações permanecem na memória.',
  'status.referenceData.loaded': 'Dados de referência carregados: {systems} sistemas, {bodies} corpos celestes, {resources} recursos e {products} produtos.',
  'help.plannedSupply': 'Os itens selecionados funcionam como marcadores até que um suprimento local ou importado seja estabelecido.',
  'help.logistics': 'Os itens atualmente atribuídos a vínculos de carga são exibidos aqui.',
  "help.biomes": "Os biomas selecionados limitam a disponibilidade de recursos inorgânicos aos recursos que podem ocorrer neles.",
  'help.present': 'Mostra se um recurso pode estar presente neste entreposto.',
  'help.producing': 'Mostra se este entreposto está configurado para produzir o recurso ou produto.',
  'help.interSystem': 'Vínculos de carga entre sistemas podem conectar entrepostos em sistemas estelares diferentes e exigem Hélio-3.',
  'help.validation': 'Erros identificam estados inválidos, avisos identificam estados incompletos ou incoerentes e informações destacam ações úteis de acompanhamento.',
  'search.input.description': 'Digite o nome ou a abreviação de um item e confirme o item que deseja pesquisar.',
  'search.results.dragInstructions': 'Mova os resultados da pesquisa com as teclas de seta. Mantenha Shift pressionado para passos maiores.',
  'referenceFatal.report.body': 'O aplicativo foi interrompido durante a verificação dos dados de referência. Diagnósticos técnicos:',
  'referenceFatal.reason.manifestFetch': 'Não foi possível recuperar o manifesto de referência.',
  'referenceFatal.reason.manifestInvalid': 'O manifesto de referência é inválido.',
  'referenceFatal.reason.manifestVersion': 'A versão do manifesto de referência não é compatível.',
  'referenceFatal.reason.buildMismatch': 'Os dados de referência pertencem a outra versão do aplicativo.',
  'referenceFatal.reason.internal': 'Não foi possível concluir a verificação de integridade dos dados de referência.',
  'common.moveUp': 'Mover {item} para cima', 'common.moveDown': 'Mover {item} para baixo', 'common.dragToReorder': 'Arraste {item} para reordenar',
  'about.description': 'Uma ferramenta para registrar redes de entrepostos de Starfield.',
  'shortcuts.action.focusSearch': 'Focar a pesquisa de itens',
  'outpost.name.label': 'Nome do entreposto', 'outpost.system.select': 'Selecione...', 'outpost.body.select': 'Selecione...',
  'outpost.referenceData.empty': 'Nenhum dado de referência de recursos encontrado para este corpo celeste.',
  'production.empty': 'Nenhum recurso local foi selecionado.',
  'matrix.action.togglePresent': 'Alternar a presença de {item}', 'matrix.action.toggleProducing': 'Alternar a produção de {item}',
  'matrix.action.toggleProducingSource': 'Alternar a produção de {item} a partir de {source}',
  'plannedSupply.remove': 'Remover {item} de Suprimento planejado', 'plannedSupply.add': 'Adicionar {item} a Suprimento planejado',
  'cargo.export.toggle': 'Alternar a exportação de {item}', 'cargo.destination.noPads': '{outpost} — nenhum vínculo de carga',
  'validation.duplicateLocalResource': '{item} aparece mais de uma vez nos recursos locais deste entreposto.',
  'validation.duplicateActiveProduction': '{item} aparece mais de uma vez na produção ativa deste entreposto.',
  'validation.duplicateExplicitPresence': '{item} aparece mais de uma vez na presença explícita de recursos deste entreposto.',
  'validation.duplicateBiome': '{item} aparece mais de uma vez na seleção de biomas deste entreposto.',
  'validation.duplicateManufacturing': '{item} aparece mais de uma vez na lista de fabricação deste entreposto.',
  'validation.duplicatePlannedSupply': '{item} aparece mais de uma vez no Suprimento planejado deste entreposto.',
  'validation.duplicateOutboundItem': '{item} aparece mais de uma vez nos itens de saída deste vínculo de carga.',
  'validation.unknownSystem': 'Este entreposto faz referência ao ID de sistema estelar desconhecido “{id}”.',
  'validation.unknownBody': 'Este entreposto faz referência ao ID de corpo celeste desconhecido “{id}”.',
  'validation.unknownLocalResource': 'Este entreposto faz referência ao ID de recurso desconhecido “{id}” nos recursos locais.',
  'validation.unknownBiome': 'Este entreposto faz referência ao ID de bioma do corpo desconhecido “{id}”.',
  'validation.unknownExplicitResource': 'Este entreposto faz referência ao ID de recurso desconhecido “{id}” na presença explícita de recursos.',
  'validation.unknownProductionResource': 'Este entreposto faz referência ao ID de recurso desconhecido “{id}” na produção ativa.',
  'validation.unknownProductionSpecies': 'Este entreposto faz referência ao ID de espécie desconhecido “{id}” na produção ativa.',
  'validation.unknownManufacturingProduct': 'Este entreposto faz referência ao ID de produto desconhecido “{id}” na lista de fabricação.',
  'validation.unknownPlannedItem': 'Este entreposto faz referência ao ID de {kind} desconhecido “{id}” em Suprimento planejado.',
  'validation.unknownOutboundItem': 'Este vínculo de carga faz referência ao ID de {kind} desconhecido “{id}” nos itens de saída.',
  'status.import.failed': 'Falha ao importar {fileName}: {reason}', 'status.import.readFailed': 'Não foi possível ler o arquivo selecionado.',
  'status.import.invalid': 'Não foi possível importar o arquivo selecionado.', 'status.import.invalidJson': 'O arquivo selecionado não contém JSON válido.',
  'status.import.invalidCollection': 'O arquivo selecionado não é uma coleção de redes válida.', 'status.import.emptyCollection': 'A coleção selecionada não contém redes.',
  'status.import.malformedEntry': 'A coleção selecionada contém uma entrada de rede malformada.',
  'status.import.duplicateNetworkId': 'A coleção selecionada contém o ID de rede duplicado “{id}”.',
  'status.import.invalidCharacter': 'O arquivo selecionado contém dados de personagem inválidos.',
  'status.import.invalidCapabilities': 'O arquivo selecionado contém dados de capacidade do personagem inválidos.',
  'status.import.invalidSkills': 'O arquivo selecionado contém dados de habilidade do personagem inválidos.',
  'status.import.invalidNetwork': 'O arquivo selecionado não é uma rede de entrepostos válida.', 'status.import.invalidOutpost': 'O arquivo selecionado contém um entreposto inválido.',
  'status.import.invalidExplicitPresence': 'O arquivo selecionado contém dados de presença explícita de recursos inválidos.',
  'status.import.invalidCargoPad': 'O arquivo selecionado contém um vínculo de carga inválido.',
  'status.import.invalidStructure': 'O arquivo selecionado contém dados de rede malformados.',
  'status.import.invalidIdentity': 'O arquivo selecionado contém um identificador estável vazio ou duplicado.',
  'status.import.fileTooLarge': 'Esta importação é grande demais para ser aberta com segurança.',
  'status.import.arrayLimitExceeded': 'Esta importação contém itens demais em uma seção.',
  'status.import.tooManyNetworks': 'Esta importação contém redes salvas demais.',
  'status.import.aggregateLimitExceeded': 'Esta importação contém itens demais para ser aberta com segurança.',
  'status.import.stringTooLong': 'Esta importação contém um valor de texto longo demais.',
  'status.referenceData.reload': 'Recarregar dados de referência', 'status.drag.reorder': 'Solte para reordenar · Esc para cancelar',
  'transfer.import.tooltip': 'Importar todas as redes de JSON',
  'history.unlinkCargoPad': 'Desvincular {outpost} / {pad}', 'history.linkCargoPad': 'Vincular {localOutpost} / {localPad} a {remoteOutpost} / {remotePad}',
  'history.changeCargoLink': 'Alterar o vínculo de {localOutpost} / {localPad} para {remoteOutpost} / {remotePad}',
  'history.renameCharacter': 'Renomear o personagem de {previousName} para {name}',
  'history.changeCharacterLevel': 'Alterar o nível do personagem de {previousLevel} para {level}', 'history.changeSkill': 'Alterar {skill} de {previousRank} para {rank}',
  'history.moveOutpost': 'Mover {outpost} para a posição {position}', 'history.moveCargoPad': 'Mover {outpost} / {pad} para a posição {position}',
  'history.addExport': 'Adicionar a exportação de {item} a {outpost} / {pad}', 'history.removeExport': 'Remover a exportação de {item} de {outpost} / {pad}',
  'history.changeCargoPadType': 'Alterar {outpost} / {pad} para {type}', 'history.renameOutpost': 'Renomear o entreposto de {previousName} para {name}',
  'history.changeSystem': 'Alterar o sistema de {outpost} para {system}', 'history.clearSystem': 'Limpar o sistema de {outpost}',
  'history.changeBody': 'Alterar o corpo celeste de {outpost} para {body}', 'history.clearBody': 'Limpar o corpo celeste de {outpost}',
  'history.addBiome': 'Adicionar seleção de bioma a {outpost}', 'history.removeBiome': 'Remover seleção de bioma de {outpost}',
  'history.addLocalResource': 'Adicionar o recurso local {resource} a {outpost}', 'history.removeLocalResource': 'Remover o recurso local {resource} de {outpost}',
  'history.addExplicitResource': 'Adicionar o recurso explícito {resource} a {outpost}', 'history.removeExplicitResource': 'Remover o recurso explícito {resource} de {outpost}',
  'history.startProducing': 'Começar a produzir {resource} em {outpost}', 'history.stopProducing': 'Parar de produzir {resource} em {outpost}',
  'history.editManufacturing': 'Editar a fabricação em {outpost}',
  'help.forContext': 'Ajuda para {context}', 'help.contextLabel': 'Ajuda para {context}',
  "help.organic.unavailablePlanet": "{resource} não está disponível nesta espécie domesticável neste planeta.",
  "help.organic.unavailableBiome": "{resource} não está disponível nesta espécie domesticável neste planeta.",
  "help.organic.unavailableBiomes": "{resource} não está disponível nesta espécie domesticável neste planeta.",
  "help.organic.availablePlanet": "{resource} está disponível em uma espécie domesticável neste planeta.",
  "help.organic.availableBiome": "{resource} está disponível em uma espécie domesticável neste planeta.",
  "help.organic.availableSelectedBiome": "{resource} está disponível em uma espécie domesticável neste planeta.",
  "help.organic.availableBiomes": "{resource} está disponível em uma espécie domesticável neste planeta.",
  'help.inorganicPresentRecorded': '{resource} consta como presente neste entreposto.', 'help.inorganicPresentPossible': '{resource} pode estar presente neste entreposto.',
  'matrix.action.xTech.add': 'Adicionar {resource} como presente',
  'matrix.tooltip.xTech.add': 'Adicione {resource} como presente. Ele pode ser extraído em qualquer entreposto se houver núcleos de energia Tec-X disponíveis.',
  'matrix.tooltip.xTech.present': '{resource} foi registrado explicitamente como presente neste entreposto.',
  'matrix.tooltip.producing.active': '{item} está sendo produzido neste entreposto.', 'matrix.tooltip.producing.inactive': '{item} não está sendo produzido neste entreposto.',
  'matrix.tooltip.manufacturing.blocked': '{item} não está sendo produzido neste entreposto devido à falta de insumos.',
  'matrix.tooltip.input.available': '{item} está disponível neste entreposto.', 'matrix.tooltip.input.unavailable': '{item} não está disponível neste entreposto.',
  'matrix.tooltip.export.active': '{item} está sendo exportado para {destinations}.',
  'search.input.label': 'Pesquisar recursos ou produtos nos seus entrepostos.', 'search.submit': 'Pesquisar item',
  'search.results.found': '{searchItem} foi encontrado em {count} {count, plural, one {entreposto} other {entrepostos}}.',
  'referenceFatal.report.subject': 'Problema nos dados de referência do rastreador de entrepostos de Starfield',
  'about.closeDialog': 'Fechar a caixa de diálogo Sobre', 'shortcuts.closeDialog': 'Fechar a caixa de diálogo Atalhos de teclado',
  'shortcuts.action.toggleNavigation': 'Mostrar ou ocultar a navegação', 'shortcuts.action.focusNavigation': 'Focar a navegação',
  'shortcuts.action.toggleValidation': 'Alternar os detalhes da validação',
  'network.reset.confirmTitle': 'REDEFINIR REDE', 'network.delete.confirmTitle': 'EXCLUIR REDE',
  'outpost.navigation.finishReshuffle': 'Concluir a reordenação dos entrepostos', 'cargo.finishReshuffle': 'Concluir a reordenação dos vínculos de carga',
  'validation.counts': '{errors} erros · {warnings} avisos · {info} informações',
  'status.dismiss': 'Dispensar a mensagem de status',
  'status.import.unsupportedCollectionSchema': 'Versão incompatível do esquema da coleção de redes: {version}',
  'status.import.unsupportedNetworkSchema': 'Versão incompatível do esquema da rede: {version}',
  'status.referenceData.failed': 'Falha ao carregar os dados de referência.', 'status.referenceData.error': 'Erro nos dados de referência: {detail}',
  'transfer.export.tooltip': 'Exportar todas as redes para JSON', 'history.importNetworks': 'Importar redes',
  'history.clearCharacterLevel': 'Limpar o nível do personagem', 'history.setCharacterLevel': 'Definir o nível do personagem como {level}',
  'search.input.placeholder': 'Pesquisar recursos ou produtos', 'search.results.flag.missingInputs': 'Insumos ausentes',
  'outpost.navigation.addWithLimit': 'Adicionar entreposto ({count} de {limit})',
  'cargo.expandAll': 'Expandir tudo', 'cargo.collapseAll': 'Recolher tudo',
  'cargo.addWithLimit': 'Adicionar vínculo de carga ({count} de {limit})', 'history.setSkill': 'Definir {skill} como {rank}',
  'cargo.interSystem.button': 'Entre sistemas',
}, [
  ['Reference data unavailable', 'Dados de referência indisponíveis'], ['Required reference data', 'Os dados de referência obrigatórios'],
  ['Reference data', 'Dados de referência'], ['reference data', 'dados de referência'], ['reference manifest', 'manifesto de referência'],
  ['could not be retrieved', 'não pôde ser recuperado'], ['could not complete', 'não pôde ser concluída'], ['is unsupported', 'não é compatível'],
  ['is invalid', 'é inválido'], ['belongs to a different app build', 'pertence a outra versão do aplicativo'],
  ['A required reference file', 'Um arquivo de referência obrigatório'], ['contains invalid JSON', 'contém JSON inválido'],
  ['has an invalid structure', 'tem uma estrutura inválida'], ['exceeds the size limit', 'excede o limite de tamanho'],
  ['does not match the manifest', 'não corresponde ao manifesto'], ['was served with the wrong content type', 'foi fornecido com o tipo de conteúdo incorreto'],
  ['Language and region', 'Idioma e região'], ['Automatic', 'Automático'], ['Locale', 'Localidade'],
  ['Keyboard Shortcuts', 'Atalhos de teclado'], ['Resource Matrix', 'Matriz de recursos'], ['Planned Supply', 'Suprimento planejado'],
  ['X-Tech Power Cores', 'Núcleos de energia Tec-X'], ['X-Tech', 'Tec-X'],
  ['Active Production', 'Produção ativa'], ['Inter-System Cargo Links', 'Vínculos de carga entre sistemas'],
  ['Inter-System Cargo Link', 'Vínculo de carga entre sistemas'], ['Cargo Links', 'Vínculos de carga'], ['Cargo Link', 'Vínculo de carga'],
  ['cargo links', 'vínculos de carga'], ['cargo link', 'vínculo de carga'], ['Outpost Management', 'Gestão de Entrepostos'],
  ['Outpost Engineering', 'Engenh. de Entrepostos'], ['Planetary Habitation', 'Habitação Planetária'],
  ['Research Methods', 'Métodos de Pesquisa'], ['Special Projects', 'Projetos Especiais'],
  ['Outpost Navigation', 'Navegação de entrepostos'], ['Outpost Details', 'Detalhes do entreposto'], ['outpost navigation', 'navegação de entrepostos'],
  ['Manufactured Products', 'Produtos fabricados'], ['Inorganic Resources', 'Recursos inorgânicos'], ['Organic Resources', 'Recursos orgânicos'],
  ['Search Results', 'Resultados da pesquisa'], ['No validation issues', 'Nenhum problema de validação'], ['validation details', 'detalhes da validação'],
  ['star system', 'sistema estelar'], ['planetary body', 'corpo celeste'], ['local resources', 'recursos locais'],
  ['active production', 'produção ativa'], ['explicit resource presence', 'presença explícita de recursos'],
  ['manufacturing list', 'lista de fabricação'], ['outbound items', 'itens de saída'],
  ['appears more than once in', 'aparece mais de uma vez em'], ['refers to unknown', 'faz referência a um'], ['unknown', 'desconhecido'],
  ['is recorded as produced', 'consta como produzido'], ['is recorded as present', 'consta como presente'], ['is not available', 'não está disponível'],
  ['is available', 'está disponível'], ['is being produced', 'está sendo produzido'], ['is not being produced', 'não está sendo produzido'],
  ['is being exported', 'está sendo exportado'], ['is not being exported', 'não está sendo exportado'], ['is being imported', 'está sendo importado'],
  ['available for extraction', 'disponível para extração'], ['available for harvesting', 'disponível para coleta'],
  ['Add items to', 'Adicionar itens a'], ['Remove all', 'Remover todo o'], ['Add manufactured product', 'Adicionar produto fabricado'],
  ['Add product', 'Adicionar produto'], ['Add outpost', 'Adicionar entreposto'], ['Delete Outpost', 'Excluir entreposto'], ['New Outpost', 'Novo entreposto'],
  ['outposts', 'entrepostos'], ['outpost', 'entreposto'], ['Outposts', 'Entrepostos'], ['Outpost', 'Entreposto'],
  ['NETWORK', 'REDE'], ['Network', 'Rede'], ['network', 'rede'], ['collection', 'coleção'],
  ['Reload', 'Recarregar'], ['Report', 'Relatar'], ['Error code', 'Código de erro'], ['Asset', 'Arquivo'], ['HTTP status', 'Status HTTP'],
  ['Media type', 'Tipo de conteúdo'], ['Manifest schema version', 'Versão do esquema do manifesto'], ['Expected dataset ID', 'ID esperado do conjunto de dados'],
  ['Actual dataset ID', 'ID real do conjunto de dados'], ['Expected hash prefix', 'Prefixo de hash esperado'], ['Actual hash prefix', 'Prefixo de hash real'],
  ['About', 'Sobre'], ['Help', 'Ajuda'], ['Close', 'Fechar'], ['Cancel', 'Cancelar'], ['cancel', 'cancelar'], ['save', 'salvar'], ['edit', 'editar'],
  ['Add', 'Adicionar'], ['Remove', 'Remover'], ['Move', 'Mover'], ['Drag', 'Arrastar'], ['Expand', 'Expandir'], ['Collapse', 'Recolher'],
  ['Show', 'Mostrar'], ['Hide', 'Ocultar'], ['History', 'Histórico'], ['Search', 'Pesquisar'], ['Workspace', 'Área de trabalho'],
  ['Import', 'Importar'], ['Export', 'Exportar'], ['Validation', 'Validação'], ['Undo', 'Desfazer'], ['Redo', 'Refazer'],
  ['Focus', 'Focar'], ['Previous', 'Anterior'], ['Next', 'Próximo'], ['Toggle', 'Alternar'], ['Character', 'Personagem'],
  ['Level', 'Nível'], ['rank', 'grau'], ['level', 'nível'], ['Active', 'Ativa'], ['Reset', 'Redefinir'], ['Delete', 'Excluir'],
  ['RESHUFFLE', 'REORDENAR'], ['Lock order', 'Bloquear a ordem'], ['Reshuffle', 'Reordenar'], ['reshuffling', 'reordenação de'],
  ['Select', 'Selecionar'], ['System', 'Sistema'], ['Body', 'Corpo celeste'], ['Solar', 'Solar'], ['Wind', 'Eólica'],
  ['Biomes', 'Biomas'], ['biome', 'bioma'], ['biomes', 'biomas'], ['Very Poor', 'Muito ruim'], ['V.Poor', 'M. ruim'],
  ['Poor', 'Ruim'], ['Normal', 'Normal'], ['Good', 'Boa'], ['None', 'Nenhuma'], ['Unknown', 'Desconhecido'],
  ['output', 'produção'], ['no modifier', 'sem modificador'], ['Item', 'Item'], ['Source', 'Origem'], ['Present', 'Presença'],
  ['Producing', 'Em produção'], ['Inputs', 'Insumos'], ['Logistics', 'Logística'], ['Inorganic', 'Inorgânico'], ['Organic', 'Orgânico'],
  ['Manufacturing', 'Fabricação'], ['Imports', 'Importações'], ['Exports', 'Exportações'], ['Unspecified', 'Não especificada'],
  ['No local resources have been selected', 'Nenhum recurso local foi selecionado'], ['No manufacturing recorded', 'Nenhuma fabricação registrada'],
  ['No imports', 'Nenhuma importação'], ['No exports', 'Nenhuma exportação'], ['No planned supply', 'Nenhum suprimento planejado'],
  ['active', 'ativo'], ['inactive', 'inativo'], ['Destination', 'Destino'], ['Unlinked', 'Sem vínculo'], ['unlinked', 'sem vínculo'],
  ['linked to', 'vinculado a'], ['Linked to', 'Vinculado a'], ['nothing', 'nada'], ['No items available to export', 'Nenhum item disponível para exportar'],
  ['No outbound cargo', 'Nenhuma carga de saída'], ['No inbound cargo', 'Nenhuma carga de entrada'], ['Standard', 'Padrão'],
  ['All', 'Todos'], ['Errors', 'Erros'], ['Warnings', 'Avisos'], ['Warning', 'Aviso'], ['Error', 'Erro'], ['Info', 'Informação'],
  ['Open', 'Abrir'], ['issues', 'problemas'], ['issue', 'problema'], ['errors', 'erros'], ['warnings', 'avisos'],
  ['requires', 'requer'], ['recorded', 'registrado'], ['missing', 'ausente'], ['Selected file', 'O arquivo selecionado'],
  ['selected file', 'arquivo selecionado'], ['selected collection', 'coleção selecionada'], ['Browser storage', 'O armazenamento do navegador'],
  ['Changes', 'As alterações'], ['Dismiss', 'Dispensar'], ['Exported', 'Exportado'], ['Imported', 'Importado'],
  ['Import failed for', 'Falha ao importar'], ['does not contain', 'não contém'], ['contains', 'contém'], ['invalid', 'inválido'],
  ['Unsupported', 'Incompatível'], ['Nothing to undo', 'Nada para desfazer'], ['Nothing to redo', 'Nada para refazer'],
  ['Rename', 'Renomear'], ['Clear', 'Limpar'], ['Set', 'Definir'], ['Change', 'Alterar'], ['Start producing', 'Começar a produzir'],
  ['Stop producing', 'Parar de produzir'], ['Available from', 'Disponível em'], ['available', 'disponível'], ['selected', 'selecionado'],
  ['Resource', 'Recurso'], ['Product', 'Produto'], ['resource', 'recurso'], ['product', 'produto'], ['Search for', 'Pesquisar'],
  ['Type an item name', 'Digite o nome de um item'], ['was found at', 'foi encontrado em'], ['was not found at any', 'não foi encontrado em nenhum'],
  ['Missing Inputs', 'Insumos ausentes'], ['Importing', 'Importando'], ['Exporting', 'Exportando'],
])
